### PR TITLE
Feature/cougar cash direct

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/209)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1Qvqz6Rl9O3Q72P9e:-Kp1Qvqz6Rl9O3Q72P9f:b-89817p) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L17)):*
> ```objc
> #define FOUND_TEXT @"Card Found"
> #define COUGAR_CASH_AD_TAG @"hasSeenCougarCashDirectAd"
> //TODO: Double check this URL
> ```

Do it

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 18 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1QxSoPaorrJZvg5ai:-Kp1QxSoPaorrJZvg5aj:b-88n3qj) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L18)):*
> ```objc
> #define COUGAR_CASH_AD_TAG @"hasSeenCougarCashDirectAd"
> //TODO: Double check this URL
> #define MFC_URL @"https://sa-dev.byu.edu/psc/ps/EMPLOYEE/HRMS/c/Y_MY_FINANCIAL_CENTER.Y_SIG_HOME_FL.GBL?page=Y_SIG_DESCR_PG1_FL"
> ```

Switch to PROD

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 143 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1R1VEV6vDJag_yWb8:-Kp1R1VEV6vDJag_yWb9:b-6oeq5t) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L143)):*
> ```objc
> }
> 
> - (IBAction)signUpForDirectTapped:(id)sender {
> ```

Remove space

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 189 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1R5SQwb25ifv6XwWi:-Kp1R5SQwb25ifv6XwWj:bjeu2f6) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L189)):*
> ```objc
> 		self.currentBalanceLabel.text = [NSString stringWithFormat:@"$%.2f", self.balance.balance];
>         if (self.balance.canAddFunds) {
>             [self.addFundsButton setTitle:@"Add Funds" forState:UIControlStateNormal];
> ```

You can do this with ternary if you'd like

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 193 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1R98mhh4G7FIk6RHA:-Kp1R98n6yyv_Yo7QjkY:bb36xad) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L193)):*
> ```objc
>             [self.addFundsButton setTitle:@"Manage Account" forState:UIControlStateNormal];
>         }
> 		self.addFundsButton.hidden = NO;
> ```

Now that it will never be hidden, you can remove this line and just make it not hidden in the storyboard I think. With that in mind, I would also default the storyboard to "Manage Account" instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 143 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1R1VEV6vDJag_yWb8:-Kp1e351bkD3YJ3Q7yfb:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L143)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove space
</blockquote></details>

Done.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 189 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1R5SQwb25ifv6XwWi:-Kp1e04ae0vNcmtWc91X:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L189)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can do this with ternary if you'd like
</blockquote></details>

Done.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 193 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1R98mhh4G7FIk6RHA:-Kp1dfN-0PJNbHviotJ_:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L193)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Now that it will never be hidden, you can remove this line and just make it not hidden in the storyboard I think. With that in mind, I would also default the storyboard to "Manage Account" instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 17 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kqj8ROdsXA4M08qzZwa:-Kqj8ROdsXA4M08qzZwb:b3hl97z) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/49e8b711f00011c0c399dcd6799008498df678e1/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L17)):*
> ```objc
> #define FOUND_TEXT @"Card Found"
> #define COUGAR_CASH_AD_TAG @"hasSeenCougarCashDirectAd"
> //TODO: Test and Double check this production URL
> ```

Do it :) And remove old url

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 18 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kp1QxSoPaorrJZvg5ai:-Kqx5kouL6wfkCFe-FW-:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/699e4575d2c98f38d59e9f1401c2ad40193e64f7/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Switch to PROD
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 17 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kqj8ROdsXA4M08qzZwa:-Kqx6D362zGAeGLQvjHo:bjzt44n) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/49e8b711f00011c0c399dcd6799008498df678e1/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it :) And remove old url
</blockquote></details>

Not working yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 17 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kqj8ROdsXA4M08qzZwa:-Kqx8BpQbsFDLnJMvuUi:babesvz) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/49e8b711f00011c0c399dcd6799008498df678e1/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L17)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Not working yet.
</blockquote></details>

Well today is our release for MFC, so do you know if Dave bishop thinks it will be ready today?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 17 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kqj8ROdsXA4M08qzZwa:-KqxD7dm1bnOvPci-KE_:bcyn3jw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/49e8b711f00011c0c399dcd6799008498df678e1/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Well today is our release for MFC, so do you know if Dave bishop thinks it will be ready today?
</blockquote></details>

I'm sorry. Wrong feature. Could you check with Dallas to see when his responsive page will be done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 17 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kqj8ROdsXA4M08qzZwa:-KqxpNd-FGVk5uKwq2aY:b-aswhjo) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/49e8b711f00011c0c399dcd6799008498df678e1/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'm sorry. Wrong feature. Could you check with Dallas to see when his responsive page will be done?
</blockquote></details>

Mark this as done after you are able to get in contact with Dallas

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by ecbrady** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 17 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Kqj8ROdsXA4M08qzZwa:-Ks4mnkLSK7DP2ZQT9li:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/31a3249b6bcc3fdb85f9a6a23b9e0a847b6d75ba/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Mark this as done after you are able to get in contact with Dallas
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 109 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Ks4ztULxsjyIyGoBhCr:-Ks4ztULxsjyIyGoBhCs:b-vrdafn) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/0e1f168445343336bcb3c3a52aeac04156b4a289/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L109)):*
> ```objc
>     } else {
>         if ([[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:MANAGE_ACCOUNT_URL]]) {
>             [[UIApplication sharedApplication] openURL:[NSURL URLWithString:MANAGE_ACCOUNT_URL]];
> ```

You can change this back. Once they fix the dang URL, everything should be good again

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 189 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Ks5--uoOH7A2s3MzHWr:-Ks5--uoOH7A2s3MzHWs:bmp04qk) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/0e1f168445343336bcb3c3a52aeac04156b4a289/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L189)):*
> ```objc
> 
> -(void)informationLoaded {
>     self.toolBarHeightConstraint.constant = self.balance.canAddCougarCashDirect? TOOLBAR_HEIGHT : 0;
> ```

Add space before ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 109 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Ks4ztULxsjyIyGoBhCr:-Ks53VGfJfFh_ep1nhBz:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/0e1f168445343336bcb3c3a52aeac04156b4a289/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L109)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can change this back. Once they fix the dang URL, everything should be good again
</blockquote></details>

Done.

---

*[byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m, line 189 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209#-Ks5--uoOH7A2s3MzHWr:-Ks53UrGJJ6U1fvRsseU:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/0e1f168445343336bcb3c3a52aeac04156b4a289/byuSuite/Apps/CougarCash/controller/CougarCashMainViewController.m#L189)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add space before ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/209)*

**Pull request merged**
