### PR TITLE
feature/jobOpenings -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/305)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsCategoriesViewController.swift, line 40 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5Vx4Rm1uTyVC68pKU5:-L5Vx4Rm1uTyVC68pKU6:bdf2dwz) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/controller/JobOpeningsCategoriesViewController.swift#L40)):*
> ```Swift
> 	//MARK: Custom Methods
> 	private func loadCategories() {
> 		JobOpeningsClient2.getJobCategories { (categories, error) in
> ```

Rename client without the `2`. Also, look for any other leftover `2`s in JobOpenings

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsPostingsViewController.swift, line 28 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5Vzk86241eArr3I6jv:-L5Vzk86241eArr3I6jw:b-8xeimw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/controller/JobOpeningsPostingsViewController.swift#L28)):*
> ```Swift
>     }
> 	
> 	override func viewWillAppear(_ animated: Bool) {
> ```

I'm seriously considering putting this in the TableDataVC... Can you see if any feature using TableDataVC DON'T do this exact thing in their viewWillAppear?

If we were to do this, we would also be moving the tableView into the ViewController (which I've been wanting to do for a while). This would obviously be on a separate branch, but look into it for me

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsCategory.swift, line 15 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5Vs6MV-Oro_HXOWecB:-L5Vs6MV-Oro_HXOWecC:bda7gxe) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsCategory.swift#L15)):*
> ```Swift
> 	var siteId: String
> 	var siteDescription: String?
> ```

Remove excess space

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsClient.swift, line 14 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5VwaL57WDbfhj9u8mM:-L5VwaL57WDbfhj9u8mN:baq7zxd) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsClient.swift#L14)):*
> ```Swift
> 	static func getJobCategories(callback: @escaping ([JobOpeningsCategory]?, ByuError?) -> Void) {
> 		let request = ByuRequest2(url: super.url(base: BASE_URL))
> 		ByuRequestManager.instance.makeRequest(request) { (response) in
> ```

inline `request` when it's this short :)

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsClient.swift, line 32 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5VwbtRACuBFQCjfoLm:-L5VwbtRACuBFQCjfoLn:bxlz1ju) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsClient.swift#L32)):*
> ```Swift
> 	
> 	static func getJobPostings(categoryId: String, callback: @escaping ([JobOpeningsFamily]?, ByuError?) -> Void) {
> 		let request = ByuRequest2(url: super.url(base: BASE_URL, queryParams: ["id": categoryId]))
> ```

You can inline this if you want. If you like it better outside, this one can stay outside. Whatever you'd prefer

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsFamily.swift, line 20 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5VvyhgDKeJXMDtsujL:-L5VsgQX-wl2xIr1CtA1:b-k50ca8) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsFamily.swift#L20)):*
> ```Swift
> 		
> 		//Check that listings is an array. Where there is only one listing, the service simply returns the one dictionary
> 		if let jobListings = dict["job_listing"] as? [[String: Any]] {
> ```

Let's save `dict["job_listing"]` before the `if let` so we don't duplicate the key

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsPosting.swift, line 22 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5VwFsI3Zx1MWSkm0fX:-L5VwFsI3Zx1MWSkm0fY:b-3jbt8a) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsPosting.swift#L22)):*
> ```Swift
> 		departmentDescription = dict["department_description"] as? String
> 		openDate = dict["posting_open_date"] as? String
> 		jobDescription = dict["job_description"] as? String
> ```

The obj-c code defaulted this variable. Match what's its doing. That might also make jobDescription non-optional

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305)*

**Comment by romrell4** [comment]
Reviewed 1 of 26 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.swift, line 34 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5W04WhEs39JEJjIfW6:-L5W04WhEs39JEJjIfW7:b6vh9qq) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.swift#L34)):*
> ```Swift
> 			descriptionView.loadHTMLString(htmlString, baseURL: nil)
> 		} else {
> 			descriptionView.isHidden = true
> ```

Why do we set this to hidden? Would this just show an empty page? Shouldn't we show some default text label saying that the posting was invalid or something?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsCategoriesViewController.swift, line 40 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5Vx4Rm1uTyVC68pKU5:-L5sxiQuTf1S8fV4bt1p:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/controller/JobOpeningsCategoriesViewController.swift#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Rename client without the `2`. Also, look for any other leftover `2`s in JobOpenings
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.swift, line 34 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5W04WhEs39JEJjIfW6:-L5sy-GLvPIKhOtqsMfu:b-9ltdvm) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.swift#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why do we set this to hidden? Would this just show an empty page? Shouldn't we show some default text label saying that the posting was invalid or something?
</blockquote></details>

I hide it so that for a posting that does not have an html string, there will not be an empty box that you can scroll up and down. A posting can have all other data except the html string and still be valid.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsPostingsViewController.swift, line 28 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5Vzk86241eArr3I6jv:-L5t1bLSqRebYIQkyRbl:beyk0io) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/controller/JobOpeningsPostingsViewController.swift#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'm seriously considering putting this in the TableDataVC... Can you see if any feature using TableDataVC DON'T do this exact thing in their viewWillAppear?

If we were to do this, we would also be moving the tableView into the ViewController (which I've been wanting to do for a while). This would obviously be on a separate branch, but look into it for me
</blockquote></details>

It looks possible, I dont think we have moved a lot of the features to use ByuTableDataViewController so I dont think it should take that long.

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsCategory.swift, line 15 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5Vs6MV-Oro_HXOWecB:-L5syQL0fhSrBH7k-puo:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsCategory.swift#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove excess space
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsClient.swift, line 14 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5VwaL57WDbfhj9u8mM:-L5syZ7Dyyo4vDn3dr3d:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsClient.swift#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

inline `request` when it's this short :)
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsClient.swift, line 32 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5VwbtRACuBFQCjfoLm:-L5szFvYxlhRZPWC9Uh-:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsClient.swift#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can inline this if you want. If you like it better outside, this one can stay outside. Whatever you'd prefer
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsFamily.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5VvyhgDKeJXMDtsujL:-L5szmPSSs0Yir9rAvPL:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsFamily.swift#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's save `dict["job_listing"]` before the `if let` so we don't duplicate the key
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsPosting.swift, line 22 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5VwFsI3Zx1MWSkm0fX:-L5t-ALOER1WvPzpwh7j:b7qxn5i) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/model/JobOpeningsPosting.swift#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

The obj-c code defaulted this variable. Match what's its doing. That might also make jobDescription non-optional
</blockquote></details>

this goes along with the comment about descriptionView.isHidden = true. If I leave this optional, then I can check in the JobOpeningsDetailViewController if it is nil or not, and if it is then I hide the descriptionView so we dont have an empty box that scrolls when no description was given. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.swift, line 34 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305#-L5W04WhEs39JEJjIfW6:-L5tQoHD3fLhssjhi7ba:bfh2brr) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.swift#L34)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

I hide it so that for a posting that does not have an html string, there will not be an empty box that you can scroll up and down. A posting can have all other data except the html string and still be valid.
</blockquote></details>

Yup. Sounds good. But what will the screen look like? Just empty?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.swift, line 34 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305#-L5W04WhEs39JEJjIfW6:-L5tnG3wxYjFvX1Zs7Bg:bg0g2ci) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/57f988557775770558433b73ea28e9c1178e1b3a/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.swift#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yup. Sounds good. But what will the screen look like? Just empty?
</blockquote></details>

it will still have the job title, id , and when it opens. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/305)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/305)*

**Pull request merged**
