### PR TITLE
hotfix/myNextClass -> dev

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/255)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 32 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255#-KtwtdFf38M2mh6516CC:-KtwtdFf38M2mh6516CD:b-cg76cj) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ad329e020b486064f43e2aec906d9922c8b64931/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L32)):*
> ```objc
> @property (nonatomic) YearTerm *currentYearTerm;
> @property (nonatomic) BOOL mapLoaded;
> @property (nonatomic) NSString *locationInTable;
> ```

Was locationInTable not able to be inlined?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 32 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255#-KtwtdFf38M2mh6516CC:-Ktx0EwIY0h2TJeO_aD-:b-n2gqn5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ad329e020b486064f43e2aec906d9922c8b64931/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Was locationInTable not able to be inlined?
</blockquote></details>

No it's used in the segue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 32 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255#-KtwtdFf38M2mh6516CC:-Ktx0LRjX67RBuO6jOWY:bdho6tg) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ad329e020b486064f43e2aec906d9922c8b64931/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L32)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

No it's used in the segue.
</blockquote></details>

Let's rename it then. Come up with a better name :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255)*

**Comment by ecbrady** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 32 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255#-KtwtdFf38M2mh6516CC:-Ktx1PlTAo8VwL6sm2QA:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ad329e020b486064f43e2aec906d9922c8b64931/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's rename it then. Come up with a better name :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/255)*

**Pull request merged**
