### PR TITLE
Hotfix/campus cameras

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/199)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusCameras/model/CameraStream.swift, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199#-KonHP5_w_LooR5tsZfR:-KonHP5_w_LooR5tsZfS:b2u11f3) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/098b6417d8b71f46ee392d77135122b5cfbd0dc1/byuSuite/Apps/CampusCameras/model/CameraStream.swift#L25)):*
> ```Swift
>         cameraStreamDescription = dict["description"] as? String
>         refreshInterval = dict["refreshInterval"] as? Int ?? MIN_INTERVAL
>         if refreshInterval < MIN_INTERVAL {
> ```

refreshInterval = max(refreshInterval, MIN_INTERVAL)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusCameras/model/CameraStream.swift, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199#-KonHP5_w_LooR5tsZfR:-KonHpGyJFPkxRQV7Yzd:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/098b6417d8b71f46ee392d77135122b5cfbd0dc1/byuSuite/Apps/CampusCameras/model/CameraStream.swift#L25)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

refreshInterval = max(refreshInterval, MIN_INTERVAL)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199)*

**Comment by ecbrady** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusCameras/model/CameraStream.swift, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199#-KonHP5_w_LooR5tsZfR:-KonI2gvXZeHLnDh_ruW:bomqxn5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/098b6417d8b71f46ee392d77135122b5cfbd0dc1/byuSuite/Apps/CampusCameras/model/CameraStream.swift#L25)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should I inline this with the previous line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusCameras/model/CameraStream.swift, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199#-KonHP5_w_LooR5tsZfR:-KonIGzzUWhCPX6LVBqe:b-5tdul5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/098b6417d8b71f46ee392d77135122b5cfbd0dc1/byuSuite/Apps/CampusCameras/model/CameraStream.swift#L25)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Should I inline this with the previous line?
</blockquote></details>

Yes. And default to 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199)*

**Comment by ecbrady** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[byuSuite/Apps/CampusCameras/model/CameraStream.swift, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199#-KonHP5_w_LooR5tsZfR:-KonJKuD6toWgf7-wRtK:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/098b6417d8b71f46ee392d77135122b5cfbd0dc1/byuSuite/Apps/CampusCameras/model/CameraStream.swift#L25)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yes. And default to 0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/199)*

**Pull request merged**
