### PR TITLE
hotfix/safewalk -> dev

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/285)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-D4gmne9vBAVuwMCD3:-L-D4gmne9vBAVuwMCD4:b-iiwdxg) (no related file):*
Keep fixing location updates

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 17 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-D4mOvWkMK2pG8Uv6O:-L-D4mOw57e5pNkrlgM7:b-lfvfq9) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L17)):*
> ```Swift
>     
>     @IBOutlet private weak var textView: UITextView!
> 	@IBOutlet private weak var phoneNumberField: UITextField!
> ```

Move this up one line (to be consistent with the UI)

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 26 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-D5-X4zNFPje4VrAsE:-L-D5-X4zNFPje4VrAsF:brsiui7) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L26)):*
> ```Swift
> 		super.viewDidLoad()
> 		
> 		let htmlString = "<style>ul {font-family: '\(textView.font?.fontName ?? "System")'; font-size:\(textView.font?.pointSize ?? 17);} h1 {font-family: '\(textView.font?.fontName ?? "System")'}</style><h1>NOTE:</h1><ul><li>After starting a SafeWalk session, <b>DO NOT</b> terminate the app.</li><li>After reporting an emergency, please lock your phone.</li><li>Tutorial: <a href = \"https://youtu.be/RFs2eh6XmT4\">SafeWalk Video</a></li></ul>"
> ```

Combine ul and h1 tags to make all text same size and font (I think a .body will do that if you just wrap your html in a <body>...</body> tag

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 28 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DQCdE2z5irQ8LDl71:-L-DQCdE2z5irQ8LDl72:bn0h0ra) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L28)):*
> ```Swift
> 		let htmlString = "<style>ul {font-family: '\(textView.font?.fontName ?? "System")'; font-size:\(textView.font?.pointSize ?? 17);} h1 {font-family: '\(textView.font?.fontName ?? "System")'}</style><h1>NOTE:</h1><ul><li>After starting a SafeWalk session, <b>DO NOT</b> terminate the app.</li><li>After reporting an emergency, please lock your phone.</li><li>Tutorial: <a href = \"https://youtu.be/RFs2eh6XmT4\">SafeWalk Video</a></li></ul>"
> 		if let data = htmlString.data(using: .utf8) {
> 			textView.attributedText = try? NSAttributedString(data: data, options: [NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType, NSCharacterEncodingDocumentAttribute: NSNumber(value: String.Encoding.utf8.rawValue)], documentAttributes: nil)
> ```

I've never had to use the NSNumber cast... Double check other places in the app to see how we normally do this

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 34 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DQHh2ynK0mbtMbGTL:-L-DQHh2ynK0mbtMbGTM:bfigw05) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L34)):*
> ```Swift
> 			if let personSummary = personSummary {
> 				self.phoneNumberField.text = personSummary.phoneNumber
> 				self.textFieldDidChange(self.phoneNumberField)
> ```

Comment about why you call this manually

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 72 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DQNQZewBzXQZrcb4B:-L-DQNQ_I26kXpU2ED2q:bluit0x) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L72)):*
> ```Swift
> 		phoneNumberField.layer.borderColor = validNumber ? UIColor.black.cgColor : UIColor.red.cgColor
> 		phoneNumberField.layer.borderWidth = validNumber ? 0.0 : 1.0
> 		phoneNumberField.layer.cornerRadius = 4
> ```

Should this one be ternary as well?

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 78 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DSjp5chTVyGMv9QvA:-L-DSjp5chTVyGMv9QvB:bq9dihs) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L78)):*
> ```Swift
>     
>     private func verifySegue() {
>         if !verifyPhoneNumber() {
> ```

Flip this `if` to get rid of the `!`

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 86 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DSo5ezLBmrB6rXOEw:-L-DSo5ezLBmrB6rXOEx:bb7phvt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L86)):*
> ```Swift
> 	
> 	private func verifyPhoneNumber() -> Bool {
> 		//Strip out al non-numeric characters to accurately measure length of number
> ```

typo

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMapViewController.swift, line 28 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DT3ztkqxogWEbK8lm:-L-DT3zu0K2lO0XyeFy0:budn56j) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMapViewController.swift#L28)):*
> ```Swift
>     
>     private var destination: SafeWalkCoordinateInfo?
> 	//******* This only stays if we choose to check userLocation in this VC
> ```

TODO: Figure out if this is necessary (and the rest of them)

---

*[byuSuite/Apps/SafeWalk/view/SafeWalk.storyboard, line 69 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DU3s8WQEGxbiTJs6F:-L-DU3s8WQEGxbiTJs6G:b-lh9dh5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/view/SafeWalk.storyboard#L69)):*
> ```XML
>         <scene sceneID="Zon-Xj-AIR">
>             <objects>
>                 <viewController id="tpC-31-dF8" customClass="SafeWalkMapViewController" customModule="byuSuite" customModuleProvider="target" sceneMemberID="viewController">
> ```

Remove the placeholder text, now that it is inaccurate will be immediately overwritten

---

*[byuSuite/Classes/Reusable/Extensions.swift, line 585 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DUJKTKq31v3YnwEjQ:-L-DUJKTKq31v3YnwEjR:bkh98zy) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Classes/Reusable/Extensions.swift#L585)):*
> ```Swift
> extension CLLocationCoordinate2D {
> 	func isWithinBounds(minLat: Double, maxLat: Double, minLong: Double, maxLong: Double) -> Bool {
> 		let lat = Double(self.latitude)
> ```

Instead, let's do this:
```swift
let (lat, long) = (Double(self.latitude), Double(self.longitude))
return lat >=minLat && lat <= maxLat && long >= minLong && long <= maxLong
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Classes/Reusable/Extensions.swift, line 585 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DUJKTKq31v3YnwEjQ:-L-DgJR5KjljwvN6RPqs:b-vg9mhk) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Classes/Reusable/Extensions.swift#L585)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead, let's do this:
```swift
let (lat, long) = (Double(self.latitude), Double(self.longitude))
return lat >=minLat && lat <= maxLat && long >= minLong && long <= maxLong
```
</blockquote></details>

With a comment above it explaining

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285)*

**Comment by ecbrady** [comment]
Review status: 5 of 8 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 17 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-D4mOvWkMK2pG8Uv6O:-L-Dgwhn1vei1lbzwfoo:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move this up one line (to be consistent with the UI)
</blockquote></details>

Done.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 26 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-D5-X4zNFPje4VrAsE:-L-DhU33kZW3BY0LuEjP:b-j8wduv) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Combine ul and h1 tags to make all text same size and font (I think a .body will do that if you just wrap your html in a <body>...</body> tag
</blockquote></details>

I thought we didn't want the same font size so that the heading is bigger like it was when it was a separate label.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 28 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DQCdE2z5irQ8LDl71:-L-Dhtj9U0S4z6qWPKQs:b-az0cd1) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I've never had to use the NSNumber cast... Double check other places in the app to see how we normally do this
</blockquote></details>

I haven't found anywhere else where we do this.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 34 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DQHh2ynK0mbtMbGTL:-L-Djw0EGhoKj97tEli8:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about why you call this manually
</blockquote></details>

Done.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 72 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DQNQZewBzXQZrcb4B:-L-DjxgtsX-LW3HNPCHI:bcdknu8) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L72)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Should this one be ternary as well?
</blockquote></details>

Because the borderWidth is 0 the cornerRadius does nothing.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 78 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DSjp5chTVyGMv9QvA:-L-DkIKJwGgYFdglcvry:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L78)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Flip this `if` to get rid of the `!`
</blockquote></details>

Done.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 86 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DSo5ezLBmrB6rXOEw:-L-DkM7fzeMOFTzzS5yT:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L86)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

---

*[byuSuite/Apps/SafeWalk/view/SafeWalk.storyboard, line 69 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DU3s8WQEGxbiTJs6F:-L-Dkmfe3m6wDwBKnoyE:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/view/SafeWalk.storyboard#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove the placeholder text, now that it is inaccurate will be immediately overwritten
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/Extensions.swift, line 585 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DUJKTKq31v3YnwEjQ:-L-DldXgLV0J1ORZRBJI:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Classes/Reusable/Extensions.swift#L585)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

With a comment above it explaining
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 26 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-D5-X4zNFPje4VrAsE:-L-Dx6onma7vPsXbSa3P:b-qb0pja) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L26)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I thought we didn't want the same font size so that the heading is bigger like it was when it was a separate label.
</blockquote></details>

Yes. I mean that there is duplicate code in the HTML. We can simplify it

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 28 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DQCdE2z5irQ8LDl71:-L-DxT9PI7pHndH_U2ZP:b-d8s1wg) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L28)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I haven't found anywhere else where we do this.
</blockquote></details>

MFC and Add/Drop both use it. Just find in project for "NSHTML"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285)*

**Comment by ecbrady** [comment]
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-D4gmne9vBAVuwMCD3:-L-Hs6JEjqL1O8wrZynz:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Keep fixing location updates
</blockquote></details>

Done.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 26 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-D5-X4zNFPje4VrAsE:-L-HtESSdi4snU43HAGe:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yes. I mean that there is duplicate code in the HTML. We can simplify it
</blockquote></details>

Done.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift, line 28 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DQCdE2z5irQ8LDl71:-L-HtZFpJalEmLGQ-_Vd:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMainViewController.swift#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

MFC and Add/Drop both use it. Just find in project for "NSHTML"
</blockquote></details>

Done.

---

*[byuSuite/Apps/SafeWalk/controller/SafeWalkMapViewController.swift, line 28 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285#-L-DT3ztkqxogWEbK8lm:-L-HthRFW1HxWrmcPsnc:b9qk73f) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e32df27468c0d2e7f49e68c30d24fe847fca504d/byuSuite/Apps/SafeWalk/controller/SafeWalkMapViewController.swift#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TODO: Figure out if this is necessary (and the rest of them)
</blockquote></details>

TODO: Eric contact Steve

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/285)*

**Pull request merged**
