### PR TITLE
hotfix/learningSuite -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/241)

### CODE REVIEW

**Comment by romrell4** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/LearningSuite/model/LSUtils.m, line 40 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/241#-KtS37tSRRmwawJx6KZL:-KtS37tSRRmwawJx6KZM:bxzhi2q) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3ac6d0defbe58379855fe592e23a01df31d9111b/byuSuite/Apps/LearningSuite/model/LSUtils.m#L40)):*
> ```objc
>     NSMutableDictionary *temp = [NSMutableDictionary dictionaryWithDictionary:@{SECTION_TITLE_KEY: @"COURSE PROGRESS"}];
>     NSMutableArray *rows = [NSMutableArray array];
>     if (currentProgress.currentProgressTitle && currentProgress.currentProgressDescription && currentProgress.currentProgressDisclaimer && currentProgress.currentProgressPoints && currentProgress.currentProgressPercent) {
> ```

Instead, either SHOW the whole thing, or DON'T SHOW the whole thing. Make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/241)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/241)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/LearningSuite/model/LSUtils.m, line 40 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/241#-KtS37tSRRmwawJx6KZL:-KtS4fs4RKvhkxbG9Po7:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3ac6d0defbe58379855fe592e23a01df31d9111b/byuSuite/Apps/LearningSuite/model/LSUtils.m#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead, either SHOW the whole thing, or DON'T SHOW the whole thing. Make sense?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/241)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/241)*

**Pull request merged**
