### PR TITLE
hotfix/myClasses -> dev

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by romrell4** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LB0dyPv-ZbkQQ1D5z9q:-LB0dyPv-ZbkQQ1D5z9r:bicjsqy) (no related file):*
On this branch, also make all the changes that Geoff should have slacked you about (merging cells for child classes, etc)

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 48 at r2](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LC5nooF7mCCaGKQsSAE:-LC5nooF7mCCaGKQsSAF:b-89817p) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e212bd6ccf952d49b618991117a729fad03d5153/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L48)):*
> ```Swift
> 	}
> 	
> 	//TODO: See if this can be removed
> ```

Do it

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by ecbrady** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LB0dyPv-ZbkQQ1D5z9q:-LCA2KKsDz5nv0e_bT51:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

On this branch, also make all the changes that Geoff should have slacked you about (merging cells for child classes, etc)
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 48 at r2](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LC5nooF7mCCaGKQsSAE:-LCA2LYlDp6oGh7S4qwo:bvguhy3) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e212bd6ccf952d49b618991117a729fad03d5153/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L48)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Can't remove it. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LB0dyPv-ZbkQQ1D5z9q:-LCB7IE_2Pps0576Y8lq:b-z70cyw) (no related file):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great. Could you test this side by side with all of the tests that Geoff ran on his? Talk to him and let me know when you've completed the tests

---

*[byuSuite/Apps/MyClasses/controller/MyClassesDetailViewController.swift, line 25 at r3](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LCB7VH384c55JaPJHUt:-LCB7VH384c55JaPJHUu:b-2q8bu9) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2eb5eead09a5da303aa4f87408321637fe11754d/byuSuite/Apps/MyClasses/controller/MyClassesDetailViewController.swift#L25)):*
> ```Swift
> 	var buildings: [CampusBuilding2]!
> 	var selectedClass: StudentScheduleClass2!
> 	var displayChildDetails: Bool = true
> ```

Does this need to be public? When is it set to true/false? Could it be computed based on the class?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesDetailViewController.swift, line 25 at r3](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LCB7VH384c55JaPJHUt:-LCFizV45hipBxeUmbH8:bn0zzj2) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2eb5eead09a5da303aa4f87408321637fe11754d/byuSuite/Apps/MyClasses/controller/MyClassesDetailViewController.swift#L25)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Does this need to be public? When is it set to true/false? Could it be computed based on the class?
</blockquote></details>

Yes it does and no it can't be computed based on the class. It is set from the previous view based on whether you are segueing from a class in the full list (set to true) or from a class from a single day's schedule (set to false). The class being passed into the segue is exactly the same from both instances but because of where we're coming from we want to display information differently here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LB0dyPv-ZbkQQ1D5z9q:-LCFjMLl2oaSdd-WwPhO:bbbcl1m) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Great. Could you test this side by side with all of the tests that Geoff ran on his? Talk to him and let me know when you've completed the tests
</blockquote></details>

He's not in today so this might have to wait until Monday but we'll get them done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LB0dyPv-ZbkQQ1D5z9q:-LCGWas11GAweUyDklSo:b-jy1wro) (no related file):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

He's not in today so this might have to wait until Monday but we'll get them done.
</blockquote></details>

Great. Do it Monday. Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by ecbrady** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LB0dyPv-ZbkQQ1D5z9q:-LCeuPSo6CK6Hr2XNVWt:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Great. Do it Monday. Thanks!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesDetailViewController.swift, line 61 at r4](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LCey3KK9Ke45r6PR5WV:-LCey3KK9Ke45r6PR5WW:bh2p235) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4c5b690782cab032564d18210e6d5f45dff05046/byuSuite/Apps/MyClasses/controller/MyClassesDetailViewController.swift#L61)):*
> ```Swift
> 		if displayChildDetails {
> 			//Format text for childClassDetailsLabel to include proper spacing
> 			let attributedString = NSMutableAttributedString(string: selectedClass.childClasses.reduce("") { "\($0)\(($1.instructor != nil && $1.instructor != selectedClass.instructor) ? "\n" + $1.instructor! + "\n" : "")\($1.daysTimeText())\n\($1.placeText())\n" })
> ```

What is this change? Did we miss a newline?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesDetailViewController.swift, line 61 at r4](https://reviewable.io/reviews/byu-oit/ios-byusuite/331#-LCey3KK9Ke45r6PR5WV:-LCez4D33OaYwuT2SESh:bkno8oy) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4c5b690782cab032564d18210e6d5f45dff05046/byuSuite/Apps/MyClasses/controller/MyClassesDetailViewController.swift#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this change? Did we miss a newline?
</blockquote></details>

I had to reformat it to get it to work properly with multiple child classes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/331)*

**Pull request merged**
