### PR TITLE
hotfix/learningSuite -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/298)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2, 3 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35IIQo2KO5SYQMD_AK:-L35IIQo2KO5SYQMD_AL:b-p2zs7i) (no related file):*
Does MyNextClass still work

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 40 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L359YhqJP_IBTZ51g6M:-L359YhqJP_IBTZ51g6N:bq36ye) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L40)):*
> ```objc
> @property (nonatomic) NSArray<NSDictionary *>   *tableViewData;                     //enrolled and instructor courses loaded into a single data structure
> @property (nonatomic) SemesterButton		    *semButton;
> @property (nonatomic) NSMutableDictionary<NSString *, NSMutableArray<LSCourse *> *> *instructorCoursesDict;
> ```

Talk to me about saving these as non-mutable

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 120 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L359racH8cirHKPq3V5:-L359racH8cirHKPq3V6:bo964jm) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L120)):*
> ```objc
> 
> -(void)createButtonFailed:(SemesterButton *)button {
> 	[self.spinner stopAnimating];
> ```

Why do we stop the spinner here, but not in the other ones?

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 189 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35AFBp00rQJy-krhM0:-L35AFBp00rQJy-krhM1:b-xlu1vq) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L189)):*
> ```objc
>             [self showError:self.error]; //will only show the details of the most recent error
>         } else {
> 			NSMutableSet<YearTerm *> *setYearTerms = [NSMutableSet set];
> ```

Put this below the comment. Also, name this `yearTermSet` instead

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 192 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35B3Y3HiLLxgHEgNVq:-L35B3Y3HiLLxgHEgNVr:bxpl6fb) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L192)):*
> ```objc
>             //one, or both, requests loaded successfully
>             if (self.enrolledCourses.count > 0) {
> 				self.studentCoursesDict = [[NSMutableDictionary alloc] init];
> ```

Duplicate logic. Move into a method

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 218 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35BFwAsJp-ebN2o4rY:-L35BFwAsJp-ebN2o4rZ:b-ot1dsf) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L218)):*
> ```objc
> 			
> 			NSArray<YearTerm *> *arrayYearTerms = [setYearTerms allObjects];
> 			arrayYearTerms = [arrayYearTerms sortedArrayUsingComparator:^NSComparisonResult(YearTerm *yearTerm1, YearTerm *yearTerm2) {
> ```

Use sort instead of sorted (which will do it inline)

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 132 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35IT-jYCdIRAlhVPbD:-L35IT-ktfFpe4Xn2tdk:b-gsgc9q) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L132)):*
> ```objc
> 
> -(void)loadData {
> 		[self getStudentCourses];
> ```

You can combine these two into a getCourses function if you want. Then you can remove some of the duplicate logic (personSummary, etc)

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 132 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35KC3A3TFDh-jpjW4y:-L35KC3A3TFDh-jpjW4z:b-d08lh2) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L132)):*
> ```objc
> 
> -(void)loadData {
> 		[self getStudentCourses];
> ```

Fix double indentation

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 231 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35NFbduQGHmK1LNTwL:-L35NFbduQGHmK1LNTwM:b-5xya2b) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L231)):*
> ```objc
> 	BOOL courseExists = NO; //at least one course object is created
> 	
> 	if (self.studentCoursesDict[yearTerm.code] != nil) {
> ```

Shouldn't you be checking if it's nil or empty? If so, you can just use `count > 0`

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 237 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35NZV0c0A375XTsyA7:-L35NZV0c0A375XTsyA8:b-34vmyd) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L237)):*
> ```objc
> 	}
> 	
> 	if (self.instructorCoursesDict[yearTerm.code] != nil) {
> ```

See above

---

*[byuSuite/Apps/LearningSuite/controller/LSInstructorsViewController.m, line 96 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35Nsk4kwu9B3VRK-fG:-L35Nsk4kwu9B3VRK-fH:b-ikruzj) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSInstructorsViewController.m#L96)):*
> ```objc
>     
>     //note
>     NSString *note = (instructor.officeLocation.length > 0) ? [NSString stringWithFormat:@"Office: %@", instructor.officeLocation] : @"";
> ```

Test this and show me what it's changing

---

*[byuSuite/Classes/Reusable/UI/SemesterButton.m, line 45 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35O0NS2HYAuFeeRrBs:-L35O0NS2HYAuFeeRrBt:b-cjtupn) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Classes/Reusable/UI/SemesterButton.m#L45)):*
> ```objc
>     semButton.selectedYearTerm = yearTerm;
>     semButton.delegate = delegate;
> 	[semButton.delegate createButtonSucceeded:semButton];
> ```

Why did we change this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 40 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L359YhqJP_IBTZ51g6M:-L3ER59LqXdkm3vxhXU6:b-4w4h5s) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Talk to me about saving these as non-mutable
</blockquote></details>

Discussed. Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 120 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L359racH8cirHKPq3V5:-L3E4hTtP3yZIFYE5cQ6:bbtg44r) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L120)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why do we stop the spinner here, but not in the other ones?
</blockquote></details>

Not needed here, removed.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 189 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35AFBp00rQJy-krhM0:-L3E60W070TOcQKWeGoD:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L189)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put this below the comment. Also, name this `yearTermSet` instead
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 192 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35B3Y3HiLLxgHEgNVq:-L3EDGRUHeV_vwQFBKlN:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L192)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Duplicate logic. Move into a method
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 218 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35BFwAsJp-ebN2o4rY:-L3E6CtFiCXtfpxgFCIk:b-l3tel9) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L218)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use sort instead of sorted (which will do it inline)
</blockquote></details>

What is that is objc? there is no [arrayYearTerms sort..] 

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 132 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35IT-jYCdIRAlhVPbD:-L3E5mFtze9oDnZj_AZn:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L132)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can combine these two into a getCourses function if you want. Then you can remove some of the duplicate logic (personSummary, etc)
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 132 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35KC3A3TFDh-jpjW4y:-L3E5mlqbsiRhA-hPted:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L132)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix double indentation
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 231 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35NFbduQGHmK1LNTwL:-L3EE0I1mWtJyJZmJMkv:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L231)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Shouldn't you be checking if it's nil or empty? If so, you can just use `count > 0`
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 237 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35NZV0c0A375XTsyA7:-L3ERQYH55z6u5rBEH3y:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L237)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSInstructorsViewController.m, line 96 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35Nsk4kwu9B3VRK-fG:-L3EFevOgz72kgm9r24c:b-i0yl8d) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Apps/LearningSuite/controller/LSInstructorsViewController.m#L96)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Test this and show me what it's changing
</blockquote></details>



It just capitalized office. 

---

*[byuSuite/Classes/Reusable/UI/SemesterButton.m, line 45 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35O0NS2HYAuFeeRrBs:-L3EGE_FqHNmkOvn77y6:b-ja61ix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Classes/Reusable/UI/SemesterButton.m#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did we change this?
</blockquote></details>

It was so we were actually notified in the delegate when the button was created. You can see it being done in the other init but they forgot to do it in this method (this one is used far less).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 218 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35BFwAsJp-ebN2o4rY:-L3ESOE3KAqh_rkjzo1d:bojrjuh) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L218)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

What is that is objc? there is no [arrayYearTerms sort..] 
</blockquote></details>

There is, you just have to save the arrayYearTerms as an NSMutableArray. Also, rename the variable to yearTermsArray

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 201 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3ESajVDpbgHFvGBb1F:-L3ESajVDpbgHFvGBb1G:b7eh9qb) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2fcdc37c51e9dc66b2d67c665a30ebd67bb0cab4/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L201)):*
> ```objc
> -(NSArray<YearTerm *>*)setupDictionary:(NSArray<LSCourse *>*)courses dict:(NSMutableDictionary<NSString *, NSMutableArray<LSCourse *> *>*)dictionary {
> 	for (LSCourse *course in courses) {
> 		//substringToIndex is used so that courses that are half term will be in the same yearterm.
> ```

Change `..that courses that are half term...` to `...that block courses...`

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 202 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3ESj99OspsZTK-3dj0:-L3ESj99OspsZTK-3dj1:biyh71h) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2fcdc37c51e9dc66b2d67c665a30ebd67bb0cab4/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L202)):*
> ```objc
> 	for (LSCourse *course in courses) {
> 		//substringToIndex is used so that courses that are half term will be in the same yearterm.
> 		if(dictionary[[course.period substringToIndex:5]] == nil) {
> ```

Add space after `if`

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 202 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3ESoCpe1pr9J5h-_1p:-L3ESoCpe1pr9J5h-_1q:b-twyyv0) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2fcdc37c51e9dc66b2d67c665a30ebd67bb0cab4/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L202)):*
> ```objc
> 	for (LSCourse *course in courses) {
> 		//substringToIndex is used so that courses that are half term will be in the same yearterm.
> 		if(dictionary[[course.period substringToIndex:5]] == nil) {
> ```

Save `dictionary[[course.period substringToIndex:5]]` as a local variable instead of using it 3 times

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 208 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3ET-poJr7T856F7xFC:-L3ET-poJr7T856F7xFD:b-jxvw94) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2fcdc37c51e9dc66b2d67c665a30ebd67bb0cab4/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L208)):*
> ```objc
> 	}
> 	NSMutableArray<YearTerm *> *yearTerms = [NSMutableArray array];
> 	for (NSString *key in dictionary.allKeys) {
> ```

use transformWithBlock (then yearTerms can be non-mutable)

---

*[byuSuite/Classes/Reusable/UI/SemesterButton.m, line 45 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35O0NS2HYAuFeeRrBs:-L3ETEMQ3y7o_lz9MHJW:b-y916em) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Classes/Reusable/UI/SemesterButton.m#L45)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

It was so we were actually notified in the delegate when the button was created. You can see it being done in the other init but they forgot to do it in this method (this one is used far less).
</blockquote></details>

Gotcha. Do any other features use this that would be affected by the change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35IIQo2KO5SYQMD_AK:-L3EZ7Xz1Pjk4sFNWzsU:bb77ufg) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Does MyNextClass still work
</blockquote></details>

Yes.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 218 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35BFwAsJp-ebN2o4rY:-L3EaGnqlGZvyd3fncLm:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/b93dcc1fe473f4afd4861e838aa86c1c7ebb0ca8/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L218)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

There is, you just have to save the arrayYearTerms as an NSMutableArray. Also, rename the variable to yearTermsArray
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 201 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3ESajVDpbgHFvGBb1F:-L3EaPlRkpBXSpSn7ALu:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2fcdc37c51e9dc66b2d67c665a30ebd67bb0cab4/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L201)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change `..that courses that are half term...` to `...that block courses...`
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 202 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3ESj99OspsZTK-3dj0:-L3EaRYoG-PJ3Wp-XMnH:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2fcdc37c51e9dc66b2d67c665a30ebd67bb0cab4/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L202)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add space after `if`
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 202 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3ESoCpe1pr9J5h-_1p:-L3EaiHLmlFGfVEPiJsx:b9irnba) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2fcdc37c51e9dc66b2d67c665a30ebd67bb0cab4/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L202)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Save `dictionary[[course.period substringToIndex:5]]` as a local variable instead of using it 3 times
</blockquote></details>

Saved the key instead of the array of courses, so we didnt have to set dictionary[[course.period substringToIndex:5]]  back to that temp array. It seemed cleaner this way.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 208 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3ET-poJr7T856F7xFC:-L3EdP3sjsyi9xsc3yx6:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/2fcdc37c51e9dc66b2d67c665a30ebd67bb0cab4/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L208)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

use transformWithBlock (then yearTerms can be non-mutable)
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/SemesterButton.m, line 45 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35O0NS2HYAuFeeRrBs:-L3EYLZwY1vm290M1Heh:ba40lkk) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1b43b3451ac9bff5054e4f23aec0aa6ea2359678/byuSuite/Classes/Reusable/UI/SemesterButton.m#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Gotcha. Do any other features use this that would be affected by the change?
</blockquote></details>

No other feature was actually using it (maybe why it wasnt noticed that it was missing that)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 201 at r6](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3F9S3A_4LL4qdv7sDE:-L3F9S3A_4LL4qdv7sDF:b-secg7x) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/97ab5dc40e0ac94c836fc50457ed3eb34f7bcd4d/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L201)):*
> ```objc
> 	for (LSCourse *course in courses) {
> 		//substringToIndex is used so that block courses will be in the same yearterm.
> 		NSString *keyForCourse = [course.period substringToIndex:5];
> ```

Test this with periods that are less than 5 characters

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 207 at r6](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3F9Y33OhhXYhjAZNAU:-L3F9Y33OhhXYhjAZNAV:b-n3oww6) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/97ab5dc40e0ac94c836fc50457ed3eb34f7bcd4d/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L207)):*
> ```objc
> 		[dictionary[keyForCourse] addObject:course];
> 	}
> 	NSArray<YearTerm *> *yearTerms =[dictionary.allKeys transformWithBlock:^id(id value) {
> ```

Add space after `=` and change the `id` parameters to what they actually should be

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 211 at r6](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3F9ek1Oq-9h92ujrTu:-L3F9ek1Oq-9h92ujrTv:bukk0la) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/97ab5dc40e0ac94c836fc50457ed3eb34f7bcd4d/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L211)):*
> ```objc
> 	}];
> 	
> 	return yearTerms;
> ```

Inline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35IIQo2KO5SYQMD_AK:-L3FASBKBsGZboh6KyIe:b1c25oy) (no related file):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Nope. Not working... Talk to me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L35IIQo2KO5SYQMD_AK:-L3FAwkve0vJFNdVxOq8:b-7cwhwn) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Nope. Not working... Talk to me
</blockquote></details>

Same functionally as master.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 201 at r6](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3F9S3A_4LL4qdv7sDE:-L3FRum0lm4ncydeL19a:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/97ab5dc40e0ac94c836fc50457ed3eb34f7bcd4d/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L201)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Test this with periods that are less than 5 characters
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 207 at r6](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3F9Y33OhhXYhjAZNAU:-L3FQQ3IgJu3Fukc7RnP:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/97ab5dc40e0ac94c836fc50457ed3eb34f7bcd4d/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L207)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add space after `=` and change the `id` parameters to what they actually should be
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 211 at r6](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3F9ek1Oq-9h92ujrTu:-L3FPuHi67YGi3IZFSoV:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/97ab5dc40e0ac94c836fc50457ed3eb34f7bcd4d/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L211)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Inline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 201 at r6](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3F9S3A_4LL4qdv7sDE:-L3FSHGDPpAUZ54yWKvy:b-8nyi3w) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/97ab5dc40e0ac94c836fc50457ed3eb34f7bcd4d/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L201)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 201 at r6](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298#-L3F9S3A_4LL4qdv7sDE:-L3FSrvk0pmg_KXfimxv:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/97ab5dc40e0ac94c836fc50457ed3eb34f7bcd4d/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L201)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/298)*

**Pull request merged**
