### PR TITLE
Ios9

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/262)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 10 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSInstructorsViewController.m, line 24 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262#-KvdNd97nhe6YRN7RQNf:-KvdNd97nhe6YRN7RQNg:b22n5xl) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4f5cef79903564dff68ba2508e5ed74716e9d113/byuSuite/Apps/LearningSuite/controller/LSInstructorsViewController.m#L24)):*
> ```objc
> #define OFFICE_LABEL        @"office"
> 
> //NOTE: AddressBook.framework/AddressBookUI.framework, ABUnknownPersonViewControllerDelegate protocol deprecated in iOS 9
> ```

Remove note

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 10 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262#-KvdNoSgec4FjCLTwGNg:-KvdNoSgec4FjCLTwGNh:ba3dfna) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4f5cef79903564dff68ba2508e5ed74716e9d113/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L10)):*
> ```objc
> 
> #import "PersonDirectorySearchViewController.h"
> #import <AddressBookUI/AddressBookUI.h>
> ```

Remove?

---

*[byuSuite/Classes/Reusable/Categories/NSString+HTML.m, line 536 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262#-KvdO-IO6RdCCjVhOLOS:-KvdO-IO6RdCCjVhOLOT:b-z0mh9a) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4f5cef79903564dff68ba2508e5ed74716e9d113/byuSuite/Classes/Reusable/Categories/NSString+HTML.m#L536)):*
> ```objc
> 
> -(NSString *)stringByUrlEncoding {
> 	//TODO: Make sure this is the right character set
> ```

Do it. Test these

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSInstructorsViewController.m, line 24 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262#-KvdNd97nhe6YRN7RQNf:-KvdOFyfvf2EOC4gRqbX:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4f5cef79903564dff68ba2508e5ed74716e9d113/byuSuite/Apps/LearningSuite/controller/LSInstructorsViewController.m#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove note
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 10 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262#-KvdNoSgec4FjCLTwGNg:-KvdOQOwwqT-ZxGNnWgj:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4f5cef79903564dff68ba2508e5ed74716e9d113/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L10)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Reusable/Categories/NSString+HTML.m, line 536 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262#-KvdO-IO6RdCCjVhOLOS:-KvdTu2rJOiHjT7g1oY3:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4f5cef79903564dff68ba2508e5ed74716e9d113/byuSuite/Classes/Reusable/Categories/NSString+HTML.m#L536)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it. Test these
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/262)*

**Pull request merged**
