### PR TITLE
feature/mapView -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/249)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 15 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSoGDOQehjA0SfjsCP:-KtSoGDOQehjA0SfjsCQ:b-l5fth8) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L15)):*
> ```Swift
> private let BYU_TOP_LEFT_COORD = CLLocationCoordinate2D(latitude: 40.255760, longitude: -111.656089)
> private let BYU_BOTTOM_RIGHT_COORD = CLLocationCoordinate2D(latitude: 40.244190, longitude: -111.643141)
> private let BUFFER = 0.25
> ```

Have we tested to make sure the buffer is still working? (annotations outside of the buffer should not get zoomed to)

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSoNIi3yy4HCzGsWkx:-KtSoNIi3yy4HCzGsWky:bg3uv5d) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L16)):*
> ```Swift
> private let BYU_BOTTOM_RIGHT_COORD = CLLocationCoordinate2D(latitude: 40.244190, longitude: -111.643141)
> private let BUFFER = 0.25
> private let COORDINATE_PADDING = 0.001
> ```

Have we tested to make sure the padding is still working? There should be some padding between the edge of the screen and the outermost annotations

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 21 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSoV6-yTSrKdqDE_i1:-KtSoV6-yTSrKdqDE_i2:b4mmscp) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L21)):*
> ```Swift
>     
>     //Outlets
>     @IBOutlet weak var mapView: MKMapView!
> ```

Perhaps we should make this create itself, rather than hooking up to segues?

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 34 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSo_Xvg0LRpDvO-st4:-KtSo_Xvg0LRpDvO-st5:b-80dx70) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L34)):*
> ```Swift
>     //MARK: MKMapViewDelegate callbacks
>     
>     //    func mapView(_ mapView: MKMapView, rendererFor overlay: MKOverlay) -> MKOverlayRenderer {
> ```

Todo?

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSojROra8xtHAaqIP5:-KtSojROra8xtHAaqIP6:b-4zbvc) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L45)):*
> ```Swift
>         var byuInframe = keepByuInFrame
>         
>         //Filter for valid annotations so that we do not crash the app if the only annotations are not on campus and are out of our valid bounds
> ```

Change comment to say "Filter for valid annotations so that we do not crash the app if the only annotations are outside of our valid bounds"

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 59 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSp-wFTw0ySYCOfi19:-KtSp-wFTw0ySYCOfi1A:brmxwl2) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L59)):*
> ```Swift
>             bottomRightCoord = BYU_BOTTOM_RIGHT_COORD
>         } else {
>             topLeftCoord = CLLocationCoordinate2D(latitude: -90, longitude: 180)
> ```

Comment here about why we do this

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 68 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSpOfzJtX4LII-olGQ:-KtSpOfzJtX4LII-olGR:bkmhn8g) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L68)):*
> ```Swift
>             }
>             
>             topLeftCoord.longitude = fmin(topLeftCoord.longitude, annotation.coordinate.longitude)
> ```

Is there not a swift function for this? Do we still have to use C? Or did they make this a swift function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 15 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSoGDOQehjA0SfjsCP:-KtX6iVDv6TNIMhMQaJZ:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Have we tested to make sure the buffer is still working? (annotations outside of the buffer should not get zoomed to)
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSoNIi3yy4HCzGsWkx:-KtX6lu95_QkQUcZAdqm:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Have we tested to make sure the padding is still working? There should be some padding between the edge of the screen and the outermost annotations
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 21 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSoV6-yTSrKdqDE_i1:-KtXB8kPlW7ztFzUFFId:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Perhaps we should make this create itself, rather than hooking up to segues?
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 34 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSo_Xvg0LRpDvO-st4:-KtXIgt_YtN6h9eiLs7k:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Todo?
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSojROra8xtHAaqIP5:-KtWqg8VsxqWU2RkOJRz:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change comment to say "Filter for valid annotations so that we do not crash the app if the only annotations are outside of our valid bounds"
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 59 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSp-wFTw0ySYCOfi19:-KtXIiuG607OUvgqmGIy:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L59)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment here about why we do this
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 68 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtSpOfzJtX4LII-olGQ:-KtWqsxO3WcOfsNIf0cC:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6d7d18ffe82ffa71fd8986779ba3d580c34535a4/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is there not a swift function for this? Do we still have to use C? Or did they make this a swift function?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 51 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtXJggnIOwbldXujPy1:-KtXJggnIOwbldXujPy2:b-iqeil6) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/08017533d2d48fddbf4cababbd816122028cb3de/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L51)):*
> ```Swift
>     
>     func mapView(_ mapView: MKMapView, rendererFor overlay: MKOverlay) -> MKOverlayRenderer {
>         return overlay is TileOverlay ? TileOverlayRenderer(overlay: overlay) : TileOverlayRenderer()
> ```

Have you tested with another overlay to see if this breaks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 51 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtXJggnIOwbldXujPy1:-KtqV6FJtI8q7fcJcfnf:b5vkusz) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/08017533d2d48fddbf4cababbd816122028cb3de/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L51)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Have you tested with another overlay to see if this breaks?
</blockquote></details>

Tested, if TileOverRenderer() is loaded then no overlay is shown and the app will continue to load the map without an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtqalP8Db14HkvoLjR_:-KtqalP8Db14HkvoLjRa:b-j3lk1c) (no related file):*
I think this is all done. Should I merge it now, or should I wait? What are the ramifications of merging this branch? Is any prod code looking at it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249#-KtqalP8Db14HkvoLjR_:-KuPbRC7-GjHYgvpEQY6:b-pit00) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think this is all done. Should I merge it now, or should I wait? What are the ramifications of merging this branch? Is any prod code looking at it?
</blockquote></details>

No production code is using this code at this point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/249)*

**Pull request merged**
