### PR TITLE
feature/SFSafariVC -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/268)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/BYUMobileAppManifest.json, line 118 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268#-KwGchivX1aEQWVe28yF:-KwGchivX1aEQWVe28yG:bm6hrgr) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f848cc2e19d0cdc570b30f939ef46f2779e8e901/byuSuite/BYUMobileAppManifest.json#L118)):*
> ```JSON
>             "Name": "Campus Shuttles",
>             "Description": "Use this feature to link to shuttle routes and schedules.",
>             "Icon": "Shuttle",
> ```

Get new icons

---

*[byuSuite/Classes/FeatureManager/FeatureManager.m, line 245 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268#-KwGdJEWfFoLDeFNfN3T:-KwGdJEWfFoLDeFNfN3U:b-2t5oik) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/c21d962f480783fc759016cfa930d4da3f49a184/byuSuite/Classes/FeatureManager/FeatureManager.m#L245)):*
> ```objc
> 		
> 		//If they want a warning AND they passed in a viewController (that we can call back with alert view stuff)
> 		if ([(NSNumber *)[[NSUserDefaults standardUserDefaults] objectForKey:WARN_EXTERNAL_KEY] boolValue] && viewController) {
> ```

Remove this from the settings page as well now

---

*[byuSuite/Classes/FeatureManager/FeatureManager.m, line 247 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268#-KwGdEO6MSnPHarXbt2A:-KwGdEO6MSnPHarXbt2B:bhv2ung) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f848cc2e19d0cdc570b30f939ef46f2779e8e901/byuSuite/Classes/FeatureManager/FeatureManager.m#L247)):*
> ```objc
>         SFSafariViewController *vc = [[SFSafariViewController alloc] initWithURL:[NSURL URLWithString:feature.targetUrl]];
>         [vc setPreferredBarTintColor:[UIColor byuNavigationBarBarTintColor]];
>         [vc setPreferredControlTintColor:[UIColor whiteColor]];
> ```

Was this already default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268)*

**Comment by alexanderboswell** [comment]
Review status: 15 of 33 files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/BYUMobileAppManifest.json, line 118 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268#-KwGchivX1aEQWVe28yF:-KwGjSAvcPQIdhGGIb0i:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f848cc2e19d0cdc570b30f939ef46f2779e8e901/byuSuite/BYUMobileAppManifest.json#L118)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Get new icons
</blockquote></details>

Done.

---

*[byuSuite/Classes/FeatureManager/FeatureManager.m, line 245 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268#-KwGdJEWfFoLDeFNfN3T:-KwGkjf9cQUxpz37SHrb:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/c21d962f480783fc759016cfa930d4da3f49a184/byuSuite/Classes/FeatureManager/FeatureManager.m#L245)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove this from the settings page as well now
</blockquote></details>

Done.

---

*[byuSuite/Classes/FeatureManager/FeatureManager.m, line 247 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268#-KwGdEO6MSnPHarXbt2A:-KwGk1J8uRdC_LJ6EMZT:bhn06ma) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f848cc2e19d0cdc570b30f939ef46f2779e8e901/byuSuite/Classes/FeatureManager/FeatureManager.m#L247)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Was this already default?
</blockquote></details>

Yes it is default. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268)*

**Comment by romrell4** [comment]
Reviewed 18 of 18 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/byuSuite/Images.xcassets/AppIcon.appiconset/Contents.json, line 142 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268#-KwGn76u2PVofnt6m3Lx:-KwGn76u2PVofnt6m3Ly:byp18fd) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f3290700a7306358c1d679b938ac6bc1c2289cd9/byuSuite/byuSuite/Images.xcassets/AppIcon.appiconset/Contents.json#L142)):*
> ```JSON
>       "filename" : "AppIcon83.5x83.5@2x.png",
>       "scale" : "2x"
>     },
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/byuSuite/Images.xcassets/AppIcon.appiconset/Contents.json, line 142 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268#-KwGn76u2PVofnt6m3Lx:-KwGo7p62_ePjgDu327V:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f3290700a7306358c1d679b938ac6bc1c2289cd9/byuSuite/byuSuite/Images.xcassets/AppIcon.appiconset/Contents.json#L142)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/268)*

**Pull request merged**
