### PR TITLE
hotfix/webViews -> dev

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/213)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 42 of 42 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift, line 102 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMKmGp_rNGp27rThL7:-KpMKmGqJm3WTii-rZCp:b-atnvs7) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift#L102)):*
> ```Swift
>      * @return      A properly formatted HTML string
>      */
>     func buildHTMLString(head: String, body: String) -> String {
> ```

Is this only called once? If so, I think we can just inline it. In fact, I would prefer this to be defined at the top as a private let and just insert the body (since that's the only thing that changes

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift, line 107 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMKtcTIyNE9tAp7v1L:-KpMKtcTIyNE9tAp7v1M:bgq0lnx) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift#L107)):*
> ```Swift
>     
>     func downloadFile() {
>         if let url = self.request?.url {
> ```

Have we tested this with a couple downloadable files?

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift, line 115 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMLHNVwEK0P7mbEXD_:-KpMLHNVwEK0P7mbEXDa:b-273jkh) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift#L115)):*
> ```Swift
>                 if response.succeeded {
>                     //NSUserDomainMask is the user's home directory --- place to install user's personal items (~)
>                     if let documentDirectoryPath = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first, let suggestedFileName = response.response?.suggestedFilename {
> ```

Should we combine with with the if above? If not, there is no else to catch this...

---

*[byuSuite/Apps/LockerRental/controller/LockerRentalTutorialWebViewController.swift, line 15 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMLpCksNYnO7lhOQvB:-KpMLpCksNYnO7lhOQvC:b-zbo93h) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LockerRental/controller/LockerRentalTutorialWebViewController.swift#L15)):*
> ```Swift
>     //MARK: Properties
>     
>     //TODO: This can be public (and delete the setter) once the rest of LockerRental is in Swift
> ```

Let's do this next. You've been in locker rental enough recently that it should be pretty easy to put it in Swift

---

*[byuSuite/Apps/PermissionToAdd/controller/PermissionToAddViewController.swift, line 13 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMM0KhJWSarTK9VeRh:-KpMM0KhJWSarTK9VeRi:b-b5ibzd) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/PermissionToAdd/controller/PermissionToAddViewController.swift#L13)):*
> ```Swift
> class PermissionToAddViewController: ByuWebViewController {
> 
>     override func viewDidLoad() {
> ```

I think we can create a ByuSimpleWebViewController which only needs a getUrl function. Thoughts?

---

*[byuSuite/Classes/byuSuite-Bridging-Header.h, line 7 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMMPoXOCGENcOqv8up:-KpMMPoXOCGENcOqv8uq:b-irwxhw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/byuSuite-Bridging-Header.h#L7)):*
> ```objc
> #import "XMLReader.h"
> #import "FSCalendar.h"
> #import "LSAnnouncement.h"
> ```

Let's try to get these out before we merge

---

*[byuSuite/Classes/Reusable/Extensions.swift, line 536 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMMWyFMQibGQRJmAgA:-KpMMWyFMQibGQRJmAgB:b8n0ex8) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/Extensions.swift#L536)):*
> ```Swift
>         let pattern = "(?<!=\")\\b((http|https):\\/\\/[\\w\\-_]+(\\.[\\w\\-_]+)+([\\w\\-\\.,@?^=%%&amp;:/~\\+#]*[\\w\\-\\@?^=%%&amp;/~\\+#])?)"
>         let regex = try? NSRegularExpression(pattern: pattern, options: [])
>         if let regex = regex {
> ```

Make this a guard let

---

*[byuSuite/Classes/Reusable/UI/ByuWebView.swift, line 31 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMNBZf5gnj4eyx-Txd:-KpMNBZf5gnj4eyx-Txe:b-br5vrw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/UI/ByuWebView.swift#L31)):*
> ```Swift
>     //MARK: UIWebViewDelegate Callbacks
>     
>     override func loadHTMLString(_ string: String, baseURL: URL?) {
> ```

We can combine this and the one beneath by using default parameters (as long as no obj-c code calls them)

---

*[byuSuite/Classes/Reusable/UI/ByuWebView.swift, line 81 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMNYx9dk7xn47-WHXz:-KpMNYxA4G_zmgMh0r5H:b6mdu00) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/UI/ByuWebView.swift#L81)):*
> ```Swift
>     private func requestFinishedOrFailed() {
>         ByuNetworkActivityIndicator.decrementActivityCount()
>         delegate = actualDelegate
> ```

Comment about what this is doing

---

*[byuSuite/Classes/Reusable/UI/ByuWebViewController.swift, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMNgFe8dXF75OLhvAt:-KpMNgFe8dXF75OLhvAu:blrqoxs) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/UI/ByuWebViewController.swift#L30)):*
> ```Swift
>     @IBOutlet weak var webView: ByuWebView!
> 
>     override func viewDidLoad() {
> ```

No need to override if there's no functionality

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift, line 102 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMKmGp_rNGp27rThL7:-KpMU6AaVqc0ypZGiHtM:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift#L102)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this only called once? If so, I think we can just inline it. In fact, I would prefer this to be defined at the top as a private let and just insert the body (since that's the only thing that changes
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift, line 107 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMKtcTIyNE9tAp7v1L:-KpMU8tY1BwuT5vhih9f:bb77ufg) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift#L107)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Have we tested this with a couple downloadable files?
</blockquote></details>

Yes.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift, line 115 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMLHNVwEK0P7mbEXD_:-KpMU_h-FMwTH2OSJOrg:bie0pqw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LearningSuite/controller/LSWebViewController.swift#L115)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Should we combine with with the if above? If not, there is no else to catch this...
</blockquote></details>

Combined. However, if it succeeded but this if let failed, wouldn't it crash because there is not response.error?

---

*[byuSuite/Apps/LockerRental/controller/LockerRentalTutorialWebViewController.swift, line 15 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMLpCksNYnO7lhOQvB:-KpMUmXn5gT1XRHhmovA:btz97c4) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LockerRental/controller/LockerRentalTutorialWebViewController.swift#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's do this next. You've been in locker rental enough recently that it should be pretty easy to put it in Swift
</blockquote></details>

On another branch?

---

*[byuSuite/Apps/PermissionToAdd/controller/PermissionToAddViewController.swift, line 13 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMM0KhJWSarTK9VeRh:-KpMV6NkRJWWWqKTTWmL:begbfg5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/PermissionToAdd/controller/PermissionToAddViewController.swift#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think we can create a ByuSimpleWebViewController which only needs a getUrl function. Thoughts?
</blockquote></details>

I'm not sure I understand what you mean. It would still need all the functionality of ByuWebViewController to control the spinners, back buttons, etc.

---

*[byuSuite/Classes/byuSuite-Bridging-Header.h, line 7 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMMPoXOCGENcOqv8up:-KpMVIxVFzNYqsZXsSJR:byyig0g) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/byuSuite-Bridging-Header.h#L7)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's try to get these out before we merge
</blockquote></details>

Will need to wait on a full LS swift rewrite.

---

*[byuSuite/Classes/Reusable/Extensions.swift, line 536 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMMWyFMQibGQRJmAgA:-KpMVii9Z4993jvnm3QF:b-x9bg4s) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/Extensions.swift#L536)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make this a guard let
</blockquote></details>

Like that?

---

*[byuSuite/Classes/Reusable/UI/ByuWebView.swift, line 31 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMNBZf5gnj4eyx-Txd:-KpMW-svLh1X9ONhDMkl:b-ur31ts) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/UI/ByuWebView.swift#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We can combine this and the one beneath by using default parameters (as long as no obj-c code calls them)
</blockquote></details>

It's still called by MyMap. 

---

*[byuSuite/Classes/Reusable/UI/ByuWebView.swift, line 81 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMNYx9dk7xn47-WHXz:-KpMWGcuvY-srGDitvXz:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/UI/ByuWebView.swift#L81)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about what this is doing
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuWebViewController.swift, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMNgFe8dXF75OLhvAt:-KpMWOLCLCNaCUjg4Gxw:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/UI/ByuWebViewController.swift#L30)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

No need to override if there's no functionality
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/LockerRental/controller/LockerRentalTutorialWebViewController.swift, line 15 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMLpCksNYnO7lhOQvB:-KpMbigwq2zpK6pL2KIO:bz4h4i3) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/LockerRental/controller/LockerRentalTutorialWebViewController.swift#L15)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

On another branch?
</blockquote></details>

Yes absolutely. Once this is merged

---

*[byuSuite/Apps/PermissionToAdd/controller/PermissionToAddViewController.swift, line 13 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMM0KhJWSarTK9VeRh:-KpMc10Hm6dojZTHxBn-:bcn82xa) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/PermissionToAdd/controller/PermissionToAddViewController.swift#L13)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I'm not sure I understand what you mean. It would still need all the functionality of ByuWebViewController to control the spinners, back buttons, etc.
</blockquote></details>

Talk to me

---

*[byuSuite/Classes/Reusable/UI/ByuWebView.swift, line 31 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMNBZf5gnj4eyx-Txd:-KpMbuDC6sMvKgafBD08:bwi4da3) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/UI/ByuWebView.swift#L31)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

It's still called by MyMap. 
</blockquote></details>

Put a TODO above this then explaining that we can combine these once there are no more obj-c references

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213)*

**Comment by ecbrady** [comment]
Review status: 33 of 42 files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/PermissionToAdd/controller/PermissionToAddViewController.swift, line 13 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMM0KhJWSarTK9VeRh:-KpMe-vO7cQysrXKOHOq:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Apps/PermissionToAdd/controller/PermissionToAddViewController.swift#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Talk to me
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuWebView.swift, line 31 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213#-KpMNBZf5gnj4eyx-Txd:-KpMcItrPJt7dc134nw9:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/446910a1f50b0e45812274af09176e510af6ee15/byuSuite/Classes/Reusable/UI/ByuWebView.swift#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put a TODO above this then explaining that we can combine these once there are no more obj-c references
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213)*

**Comment by romrell4** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/213)*

**Pull request merged**
