### PR TITLE
Hotfix/campus cameras

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/183)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasDetailViewController.swift, line 52 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU7v3SRW1rCvHWVMZE:-KlU7v3SRW1rCvHWVMZF:b-tk35pi) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasDetailViewController.swift#L52)):*
> ```Swift
>                     
>                     //Sets image frame to be the width of the page, finds the correct height based on the proportions of the image, and then sticks it under the navbar (+ 20 so that it takes into account the top status bar)
>                     self.feed.frame = CGRect(x: 0, y: (self.navigationController?.navigationBar.frame.size.height)! + 20, width: self.view.frame.size.width, height: (self.view.frame.size.width * ratio))
> ```

Don't use the "!". Just do "?? 0" or something so that the app doesn't crash

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasDetailViewController.swift, line 75 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU85NWU9UVTE7q9uXD:-KlU85NWU9UVTE7q9uXE:bkmobn4) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasDetailViewController.swift#L75)):*
> ```Swift
>     }
>     
>     //This method cannot be private in order for the timer's selector to reach it. It
> ```

Unfinished comment?

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift, line 11 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU5qDsDzu9-VTDHPzB:-KlU5qDsDzu9-VTDHPzC:b-90t2rz) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift#L11)):*
> ```Swift
> import UIKit
> 
> class CampusCamerasListViewController: ByuViewController2, UITableViewDataSource {
> ```

Could we use TableData here? Or would it be more complicated?

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU5NWemaRDJno2XlL8:-KlU5NWemaRDJno2XlL9:bmgwr59) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift#L25)):*
> ```Swift
>         super.viewDidLoad()
> 
>         getCameraStreams()
> ```

lets call it loadCameraStreams (normally a "get" function returns a value, where a "load" function loads up a previously defined variable)

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift, line 28 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU7WAK9KrNMzrKiLka:-KlU7WAK9KrNMzrKiLkb:bt9jdtw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift#L28)):*
> ```Swift
>     }
>     
>     override func viewWillAppear(_ animated: Bool) {
> ```

I can't remember if we do this in the viewWillAppear or viewDidAppear. Do a quick check and tell me how many features use each method for deselecting the selected row

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 31 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU6nppm5pvjTZubOPy:-KlU6nppm5pvjTZubOPz:b-orn07f) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/byuSuite.xcodeproj/project.pbxproj#L31)):*
> ```
> 		032E518A1D26DD0600D455F5 /* PrintersMapViewController.m in Sources */ = {isa = PBXBuildFile; fileRef = 032E51831D26DD0600D455F5 /* PrintersMapViewController.m */; };
> 		032E518C1D26DD0600D455F5 /* PrintersFilterViewController.m in Sources */ = {isa = PBXBuildFile; fileRef = 032E51871D26DD0600D455F5 /* PrintersFilterViewController.m */; };
> 		0345DBF21EDDCD6200821A29 /* ByuCameraStream.m in Sources */ = {isa = PBXBuildFile; fileRef = 0345DBED1EDDCD6200821A29 /* ByuCameraStream.m */; };
> ```

Shouldn't this one have been removed? Did you remove the old classes from the project?

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 593 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU6uAQ2ESE7oIcJT2o:-KlU6uAQ2ESE7oIcJT2p:buo9nmt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/byuSuite.xcodeproj/project.pbxproj#L593)):*
> ```
> 		032E51871D26DD0600D455F5 /* PrintersFilterViewController.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = PrintersFilterViewController.m; sourceTree = "<group>"; };
> 		0345DBEC1EDDCD6200821A29 /* ByuCameraStream.h */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.h; path = ByuCameraStream.h; sourceTree = "<group>"; };
> 		0345DBED1EDDCD6200821A29 /* ByuCameraStream.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = ByuCameraStream.m; sourceTree = "<group>"; };
> ```

Same here

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 1649 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU6wxnqPN3HQJT6PVd:-KlU6wxnqPN3HQJT6PVe:bfz55hq) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/byuSuite.xcodeproj/project.pbxproj#L1649)):*
> ```
> 			isa = PBXGroup;
> 			children = (
> 				0345DBEC1EDDCD6200821A29 /* ByuCameraStream.h */,
> ```

Remove these if you're done with them

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 3066 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU70Kpy-iyNtwAfGpz:-KlU70Kpy-iyNtwAfGq-:b3uf83z) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/byuSuite.xcodeproj/project.pbxproj#L3066)):*
> ```
> 				311CD60C1E54E331005B52A7 /* CampusCameraClient.h */,
> 				311CD60D1E54E331005B52A7 /* CampusCameraClient.m */,
> 				0345DBF81EDDD5E700821A29 /* CampusCameraClient2.swift */,
> ```

Can you remove the CampusCameraClient.h and .m? Or are they still being used in testing center?

---

*[byuSuite/Classes/Reusable/Clients/CampusCameraClient2.swift, line 9 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU7KhrJmwJfrZbxSit:-KlU7KhrJmwJfrZbxSiu:bftd9vk) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Classes/Reusable/Clients/CampusCameraClient2.swift#L9)):*
> ```Swift
> //
> 
> import UIKit
> ```

Remove unneeded import

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasDetailViewController.swift, line 52 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU7v3SRW1rCvHWVMZE:-KlUDCuG3oTBXjpqFf2n:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasDetailViewController.swift#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't use the "!". Just do "?? 0" or something so that the app doesn't crash
</blockquote></details>

Done.

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasDetailViewController.swift, line 75 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU85NWU9UVTE7q9uXD:-KlUDKBMYcfswidRbsHn:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasDetailViewController.swift#L75)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Unfinished comment?
</blockquote></details>

Done.

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift, line 11 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU5qDsDzu9-VTDHPzB:-KlUDOc1xPh5m4RCSASY:b-61j9va) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could we use TableData here? Or would it be more complicated?
</blockquote></details>

I thought about it but ultimately chose not to since we only implement the two methods anyways and would still need to override cellForRowAt... Using tableData would add a few lines when setting up the tableData and cellForRowAt would be slightly more robust. 

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU5NWemaRDJno2XlL8:-KlUDnG2fw4HDlV2_dRM:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift#L25)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

lets call it loadCameraStreams (normally a "get" function returns a value, where a "load" function loads up a previously defined variable)
</blockquote></details>

Done.

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift, line 28 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU7WAK9KrNMzrKiLka:-KlUE3s5ra_5H9_qJtmp:b-n22gow) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I can't remember if we do this in the viewWillAppear or viewDidAppear. Do a quick check and tell me how many features use each method for deselecting the selected row
</blockquote></details>

In every instance where we use it in swift it's viewWillAppear

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 31 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU6nppm5pvjTZubOPy:-KlUE7k77vlvN646ZccV:bsfnrp0) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/byuSuite.xcodeproj/project.pbxproj#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Shouldn't this one have been removed? Did you remove the old classes from the project?
</blockquote></details>

No. The Objective-c is still used by the objective-c reusable client which is still used by testing center.

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 593 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU6uAQ2ESE7oIcJT2o:-KlUEECYAVHEkLxaoqVX:b-q64pkt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/byuSuite.xcodeproj/project.pbxproj#L593)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

See above.

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 1649 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU6wxnqPN3HQJT6PVd:-KlUEFljbc2mXLTwTwsE:b-q64pkt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/byuSuite.xcodeproj/project.pbxproj#L1649)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove these if you're done with them
</blockquote></details>

See above.

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 3066 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU70Kpy-iyNtwAfGpz:-KlUEHhm6uu_Pry-rdvq:b-q64pkt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/byuSuite.xcodeproj/project.pbxproj#L3066)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can you remove the CampusCameraClient.h and .m? Or are they still being used in testing center?
</blockquote></details>

See above.

---

*[byuSuite/Classes/Reusable/Clients/CampusCameraClient2.swift, line 9 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU7KhrJmwJfrZbxSit:-KlUEPDWDoIeszx24J-E:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Classes/Reusable/Clients/CampusCameraClient2.swift#L9)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove unneeded import
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift, line 11 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU5qDsDzu9-VTDHPzB:-KlUGkZ5RyRNKHiTExF_:bvogwxw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift#L11)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I thought about it but ultimately chose not to since we only implement the two methods anyways and would still need to override cellForRowAt... Using tableData would add a few lines when setting up the tableData and cellForRowAt would be slightly more robust. 
</blockquote></details>

Gotcha. I've been thinking that it might be smart to add a really simple way of creating a TableData with a list of objects (no overhead) for these exact scenarios. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift, line 11 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183#-KlU5qDsDzu9-VTDHPzB:-KlUPRGKY2Rrt8tjLG-f:b-dditbe) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/e0996e64c91c5266bd39f39b14d8df53e6d2dae1/byuSuite/Apps/CampusCameras/controller/CampusCamerasListViewController.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Gotcha. I've been thinking that it might be smart to add a really simple way of creating a TableData with a list of objects (no overhead) for these exact scenarios. What do you think?
</blockquote></details>

The challenge is that each feature that is using objects instead of TableData will generally use them in such unique ways. I don't see that we'll really be able to simplify all that much. Like here we'd still need to add extra logic to save the objects in the tableData. The only method we'd be able to remove is numberOfRows. We'd still need cellForRow with added logic to get the objects out of the new tableData.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/183)*

**Pull request merged**
