### PR TITLE
hotfix/3dtouch -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/336)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[byuSuite/byuSuite-Info.plist, line 105 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/336#-LBveIcWA0jYmLaNMn33:-LBveIcWA0jYmLaNMn34:bin51gq) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/070f1ba76ad49d33659a0454ca84740783604a13/byuSuite/byuSuite-Info.plist#L105)):*
> ```XML
> 			<string>cougarCash</string>
> 		</dict>
> 		<dict>
> ```

Can you move this up to the top? I believe it's now our most used feature. Also, it looks like the new order is:

YTime
Learning Suite
Cougar Cash
Testing Center
ID Card

Could you also add Testing Center? Are you allowed to have 5?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/336)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/byuSuite-Info.plist, line 105 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/336#-LBveIcWA0jYmLaNMn33:-LBviDfJ-C6YHZkr7dmK:b-k6stro) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/070f1ba76ad49d33659a0454ca84740783604a13/byuSuite/byuSuite-Info.plist#L105)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can you move this up to the top? I believe it's now our most used feature. Also, it looks like the new order is:

YTime
Learning Suite
Cougar Cash
Testing Center
ID Card

Could you also add Testing Center? Are you allowed to have 5?
</blockquote></details>

Yes, I can do that. It is limited to 4 so we will have to cut one. Do we really need each of them to say "Open" in front of the feature? Also, I think we should look into having the user be able to customize this and we can just leave these as the defaults if they dont change them. 


---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/336)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/byuSuite-Info.plist, line 105 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/336#-LBveIcWA0jYmLaNMn33:-LBvkW3cA0goaAgm5L3p:b-bp4pjx) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/070f1ba76ad49d33659a0454ca84740783604a13/byuSuite/byuSuite-Info.plist#L105)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

Yes, I can do that. It is limited to 4 so we will have to cut one. Do we really need each of them to say "Open" in front of the feature? Also, I think we should look into having the user be able to customize this and we can just leave these as the defaults if they dont change them. 


</blockquote></details>

Remove "Open". Yes, can you look into customizing them? Add that to the VTB and get to it whenever you're done with the more pressing pull requests. Let's get this one merged, though

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/336)*

**Comment by alexanderboswell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/byuSuite-Info.plist, line 105 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/336#-LBveIcWA0jYmLaNMn33:-LBvnuN14jVRLvVaU6Pf:b-nvn3cl) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/070f1ba76ad49d33659a0454ca84740783604a13/byuSuite/byuSuite-Info.plist#L105)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove "Open". Yes, can you look into customizing them? Add that to the VTB and get to it whenever you're done with the more pressing pull requests. Let's get this one merged, though
</blockquote></details>

Done and I put that on the VTB.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/336)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/336)*

**Pull request merged**
