### PR TITLE
dev -> master

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/271)

### CODE REVIEW

**Comment by romrell4** [comment]
Review status: 0 of 145 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwppXDDC0tmjjemDLXI:-KwppXDDC0tmjjemDLXJ:bgsdnm5) (no related file):*
Get marking icon (1024x1024) for iTunesConnect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 135 of 145 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: 137 of 145 files reviewed at latest revision, 8 unresolved discussions.

---

*[byuSuite/Apps/MyMap/controller/MyMapScheduleViewController.m, line 140 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwprlldDEhafVTaf0-8:-KwprlldDEhafVTaf0-9:bb6vuto) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6bc1af4a26415752384f4a9cf7d67890597cd941/byuSuite/Apps/MyMap/controller/MyMapScheduleViewController.m#L140)):*
> ```objc
>     
>     [ByuCredentialManager getPersonSummaryWithCallback:^(PersonSummary *personSummary, ByuError *error) {
>         if (error) {
> ```

Flop

---

*[byuSuite/Classes/ByuRequest/ByuRequest.m, line 51 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwptNFhPn6TA0GOFSRE:-KwptNFhPn6TA0GOFSRF:b-962n95) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6bc1af4a26415752384f4a9cf7d67890597cd941/byuSuite/Classes/ByuRequest/ByuRequest.m#L51)):*
> ```objc
> 
> -(void)startAsynchronousWithCompletionHandler:(ByuRequestCompletionHandler)completionHandler {
>     [self setupRequestWithCallback:^(ByuError *error) {
> ```

Reformat with tabs

---

*[byuSuite/Classes/ByuRequest/ByuRequest.m, line 115 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwpu3gUAIAuokjNjYPb:-Kwpu3gUAIAuokjNjYPc:biu2gjo) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/7f53ee0bd11e13a038160fd003d0f157093cdc14/byuSuite/Classes/ByuRequest/ByuRequest.m#L115)):*
> ```objc
> 	if (self.authMethod == OAUTH) {
> 		[ByuCredentialManager getOauthTokenWithCallback:^(OauthToken *token, ByuError *error) {
> 			if (error) {
> ```

Flop `if (token) {`

---

*[byuSuite/Classes/CredentialManager/Authentication/OauthToken.swift, line 43 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwpzRge78Wbg4clVbJg:-KwpzRge78Wbg4clVbJh:b-lorc4z) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/fa5b0e27ed013d4c28771a62815608ca895a9461/byuSuite/Classes/CredentialManager/Authentication/OauthToken.swift#L43)):*
> ```Swift
>     @objc func getNetId() -> String? {
>         //The idToken is period delimited. The second "part" is a base64 encoded json object which has the netId in it.
>         if let encoding = idToken?.components(separatedBy: ".")[1] {
> ```

Catch error here?

---

*[byuSuite/Classes/FeatureManager/FeatureManager.m, line 14 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwq0NHkQMvKJUK3TMya:-Kwq0NHkQMvKJUK3TMyb:byquu61) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/5fc8d105ac25a4fae07b18517ef356c304911123/byuSuite/Classes/FeatureManager/FeatureManager.m#L14)):*
> ```objc
> #import "NSArray+higherOrder.h"
> #import <SafariServices/SafariServices.h>
> #import "UIColor+ByuColors.h"
> ```

Do we need this?

---

*[byuSuite/Classes/Reusable/Clients/ControlDates/YearTerm2.swift, line 38 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwq10UYhCf6gApVad1L:-Kwq10UYhCf6gApVad1M:b-1uevq1) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/8db30ad2c07d6112d0bdc6300414c0a375dc5abd/byuSuite/Classes/Reusable/Clients/ControlDates/YearTerm2.swift#L38)):*
> ```Swift
>         if let yearTerm = yearTerm {
>             let index = yearTerm.index(yearTerm.startIndex, offsetBy: 4)
>             if let year = Int(yearTerm.substring(to: index)),
> ```

Test this

---

*[byuSuite/Classes/Reusable/UI/ByuWebViewController.swift, line 23 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwq1BBjlM4ULd5XB_yq:-Kwq1BBkJZ3te9-Qd1yv:basyb8u) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/5fc8d105ac25a4fae07b18517ef356c304911123/byuSuite/Classes/Reusable/UI/ByuWebViewController.swift#L23)):*
> ```Swift
>  */
> 
> class ByuWebViewController: ByuViewController2, UIWebViewDelegate {
> ```

Do we still use this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: 137 of 145 files reviewed at latest revision, 8 unresolved discussions.

---

*[byuSuite/Apps/MyMap/controller/MyMapScheduleViewController.m, line 140 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwprlldDEhafVTaf0-8:-KwqYG5X4weFSRE4JrCO:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6bc1af4a26415752384f4a9cf7d67890597cd941/byuSuite/Apps/MyMap/controller/MyMapScheduleViewController.m#L140)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Flop
</blockquote></details>

Done.

---

*[byuSuite/Classes/ByuRequest/ByuRequest.m, line 51 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwptNFhPn6TA0GOFSRE:-KwqYNcvMQitIjVb9qB7:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6bc1af4a26415752384f4a9cf7d67890597cd941/byuSuite/Classes/ByuRequest/ByuRequest.m#L51)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reformat with tabs
</blockquote></details>

Done.

---

*[byuSuite/Classes/ByuRequest/ByuRequest.m, line 115 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwpu3gUAIAuokjNjYPb:-KwqYZviy292Sfm2C-sU:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/7f53ee0bd11e13a038160fd003d0f157093cdc14/byuSuite/Classes/ByuRequest/ByuRequest.m#L115)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Flop `if (token) {`
</blockquote></details>

Done.

---

*[byuSuite/Classes/CredentialManager/Authentication/OauthToken.swift, line 43 at r3](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwpzRge78Wbg4clVbJg:-Kwq_Jq6ESj41wjlAeY8:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/fa5b0e27ed013d4c28771a62815608ca895a9461/byuSuite/Classes/CredentialManager/Authentication/OauthToken.swift#L43)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Catch error here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 8 of 145 files at r1, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[byuSuite/Classes/CredentialManager/Authentication/OauthTokenClient.swift, line 21 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqbF1xiG9k5k9C43Q1:-KwqbF1xiG9k5k9C43Q2:bl8sigt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/CredentialManager/Authentication/OauthTokenClient.swift#L21)):*
> ```Swift
> 	}
> 	
> 	@objc static func getToken(authCode: String, production: Bool, callback: @escaping (OauthToken?, ByuError?) -> Void) {
> ```

Remove @objc and pass in Stage instead of Bool for production

---

*[byuSuite/Classes/CredentialManager/Gro/GroClient.swift, line 22 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqc2IYQ5MofRiQ80CX:-Kwqc2IYQ5MofRiQ80CY:b7qyzy2) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/CredentialManager/Gro/GroClient.swift#L22)):*
> ```Swift
>         //Get a token using client credentials. The GRO web service is not currently self-service, and so if you pass a token that is authorized for a certain user, it will return an error unless that user is part of the GRO group's administrators. We have attached a GRO admin as the client_owner of the mobile app's WSO2 application, and so a client_credentials token will allow a user access to know whether or not they are a member of the GRO group. This will only work if the non-entity "BYU Official Mobile App" (setup and owned by Eric Romrell) is an admin to the GRO group being queried.
>         OauthTokenClient.getClientCredentialsToken { (token, error) in
>             if let token = token, let authHeaderValue = token.getAuthorizationString() {
> ```

Combine

---

*[byuSuite/Classes/CredentialManager/PersonSummary/PersonSummaryClient.swift, line 26 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqcJkMtp7Fy3jmjgx_:-KwqcJkMtp7Fy3jmjgxa:bfura0t) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/CredentialManager/PersonSummary/PersonSummaryClient.swift#L26)):*
> ```Swift
>                     }
>                 }
>             }
> ```

Add else

---

*[byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m, line 16 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqcSKb06dkEDn5BmY1:-KwqcSKb06dkEDn5BmY2:ba3dfna) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m#L16)):*
> ```objc
> #import "byuSuite-Swift.h"
> #import <MessageUI/MessageUI.h>
> #import <SafariServices/SafariServices.h>
> ```

Remove?

---

*[byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m, line 52 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqcdh0irxyyDbA1pVU:-Kwqcdh0irxyyDbA1pVV:bpgqj9r) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m#L52)):*
> ```objc
>         [MainScreenFavoritesViewController launchFeature:featureToLaunch];
>     }
>     
> ```

Reformat

---

*[byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m, line 152 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqd3JZu2rWk8jxfoZB:-Kwqd3JZu2rWk8jxfoZC:b-a0amhw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m#L152)):*
> ```objc
> -(void)authCodeReceived {
> 	self.loggedInLabel.text = @"Logging in...";
> 	[self dismissViewControllerAnimated:true completion:nil];
> ```

Move to LoginHandler

---

*[byuSuite/Classes/MainScreen/MainScreenSettingsViewController.m, line 52 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqdnm0j9i4GdoItBCH:-Kwqdnm0j9i4GdoItBCI:boe8zjj) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/MainScreen/MainScreenSettingsViewController.m#L52)):*
> ```objc
> 	
> 	UITableViewCell *cell;
> 		cell = [tableView dequeueReusableCellWithIdentifier:@"DetailCell"];
> ```

reformat

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 42 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqe5Md3sDOAYjTAMn0:-Kwqe5Md3sDOAYjTAMn1:bpgqj9r) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L42)):*
> ```Swift
>         }
>     }
>     
> ```

Reformat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[byuSuite/Classes/CredentialManager/Authentication/OauthTokenClient.swift, line 21 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqbF1xiG9k5k9C43Q1:-KwqfhYwdD2TD4hzg-1O:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/CredentialManager/Authentication/OauthTokenClient.swift#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove @objc and pass in Stage instead of Bool for production
</blockquote></details>

Done.

---

*[byuSuite/Classes/CredentialManager/Gro/GroClient.swift, line 22 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqc2IYQ5MofRiQ80CX:-KwqfsL6-znrZWBUkH3J:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/CredentialManager/Gro/GroClient.swift#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Combine
</blockquote></details>

Done.

---

*[byuSuite/Classes/CredentialManager/PersonSummary/PersonSummaryClient.swift, line 26 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqcJkMtp7Fy3jmjgx_:-Kwqg2LQanNz1x7Odl21:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/CredentialManager/PersonSummary/PersonSummaryClient.swift#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add else
</blockquote></details>

Done.

---

*[byuSuite/Classes/FeatureManager/FeatureManager.m, line 14 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwq0NHkQMvKJUK3TMya:-Kwqg9608JhiCUWGIY8x:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/5fc8d105ac25a4fae07b18517ef356c304911123/byuSuite/Classes/FeatureManager/FeatureManager.m#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

Done.

---

*[byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m, line 16 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqcSKb06dkEDn5BmY1:-KwqgEiDzQ2DKMjQZ_0G:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

---

*[byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m, line 52 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqcdh0irxyyDbA1pVU:-KwqgJn4dMIcxRu6dTaR:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reformat
</blockquote></details>

Done.

---

*[byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m, line 152 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqd3JZu2rWk8jxfoZB:-KwqgYZ4YiT0RoXfjfSJ:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m#L152)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move to LoginHandler
</blockquote></details>

Done.

---

*[byuSuite/Classes/MainScreen/MainScreenSettingsViewController.m, line 52 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqdnm0j9i4GdoItBCH:-Kwqgg_K5RrNjXoNR2gP:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/MainScreen/MainScreenSettingsViewController.m#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

reformat
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/Clients/ControlDates/YearTerm2.swift, line 38 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwq10UYhCf6gApVad1L:-Kwqj35B_W9x2MlNUcJR:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/8db30ad2c07d6112d0bdc6300414c0a375dc5abd/byuSuite/Classes/Reusable/Clients/ControlDates/YearTerm2.swift#L38)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Test this
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift, line 42 at r5](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwqe5Md3sDOAYjTAMn0:-KwqgsWM3Fmgl7VT5RGN:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/806fd6ff7747b136e116843e700153956830ca4a/byuSuite/Classes/Reusable/UI/ByuMapViewController2.swift#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reformat
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/ByuWebViewController.swift, line 23 at r4](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-Kwq1BBjlM4ULd5XB_yq:-KwqhUQz-aZSRi73NABT:bwbd23b) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/5fc8d105ac25a4fae07b18517ef356c304911123/byuSuite/Classes/Reusable/UI/ByuWebViewController.swift#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we still use this?
</blockquote></details>

Yes, still being used by locker rental.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 1 of 145 files at r1, 8 of 8 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqnY4UNU1yWhJzm8vh:-KwqnY4UNU1yWhJzm8vi:b1svqo2) (no related file):*
Are we moving all internal webpage launches to an internal SFSafariViewController, correct?

-  Move Alumni external website launch to an internal SFSafariViewController
-  Move honor code websites launch to internal SFSafarViewController
- Move "Sign up for Cougar Cash Direct" to internal SFSafariViewController
-  Department Directory has a url for each department, that can be opened in an internal SFSafariViewController
-  When loading finals schedule, there is a gap between when the spinner stops and the data is loaded (on master too) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqnY4UNU1yWhJzm8vh:-KwqtMb9qVWbRSRHC8uZ:bl6lcql) (no related file):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

Are we moving all internal webpage launches to an internal SFSafariViewController, correct?

-  Move Alumni external website launch to an internal SFSafariViewController
-  Move honor code websites launch to internal SFSafarViewController
- Move "Sign up for Cougar Cash Direct" to internal SFSafariViewController
-  Department Directory has a url for each department, that can be opened in an internal SFSafariViewController
-  When loading finals schedule, there is a gap between when the spinner stops and the data is loaded (on master too) 

</blockquote></details>

- Move Copyright website launch to an internal SFSafariViewController.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqnY4UNU1yWhJzm8vh:-KwqvxIS48S7CLy0rfQ_:b-avtc8k) (no related file):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

- Move Copyright website launch to an internal SFSafariViewController.
</blockquote></details>

- Started on a new branch feature/internalSafariViewController

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwqnY4UNU1yWhJzm8vh:-KwrcSLI35mf_uC2U7am:b4c9lyr) (no related file):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

- Started on a new branch feature/internalSafariViewController
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KwuQleb_DyrgcATHZgz:-KwuQleb_DyrgcATHZh-:b-ayw4h1) (no related file):*
Cougar cash is not using internal SafariViewController on dev right now, changes are made in the branch that erik is on for cougar cash though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 1 of 145 files at r1, 1 of 1 files at r10, 38 of 39 files at r11.
Review status: 187 of 188 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 1 of 39 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/YTime/model/YTimePunch.swift, line 12 at r13](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KxKtV18h_-XpfizCc_-:-KxKtV18h_-XpfizCc_0:b-1uevq1) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cd8b29656fe84534366218df7738362430b1e37a/byuSuite/Apps/YTime/model/YTimePunch.swift#L12)):*
> ```Swift
> 
> private let dateFormat = DateFormatter.defaultDateFormat("HH.mm.ss.SSSSSS")
> private let returnDateFormat = DateFormatter.defaultDateFormat("yyyy-MM-dd HH.mm.ss")
> ```

Test this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: 186 of 189 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/YTime/model/YTimePunch.swift, line 12 at r13](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KxKtV18h_-XpfizCc_-:-KxOe_uDiCv13sgDT_d2:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cd8b29656fe84534366218df7738362430b1e37a/byuSuite/Apps/YTime/model/YTimePunch.swift#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Test this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r15, 1 of 1 files at r18, 2 of 2 files at r19.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KxOjqm6O2xuqAaHn13N:-KxOjqm7vHvCfy-YT0Jn:b-io4pse) (no related file):*
Fix error with refreshing token

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r20.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KxTMAshlLMowOrd2eHN:-KxTMAshlLMowOrd2eHO:bz621yb) (no related file):*
Have Alex push his code including `loginFailed:error`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: 185 of 189 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KxTMAshlLMowOrd2eHN:-KxTR3SvVIiUYfQofvdZ:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Have Alex push his code including `loginFailed:error`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by alexanderboswell** [comment]
Review status: 185 of 189 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271#-KxOjqm6O2xuqAaHn13N:-KxTR62jMLr_EvFS0CbQ:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix error with refreshing token
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r21.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r22.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/271)*

**Pull request merged**
