### PR TITLE
feature/alumni -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/280)

### CODE REVIEW

**Comment by alexanderboswell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280#-KyXLqSWWZRteTmmWCSZ:-KyXLqSWWZRteTmmWCS_:bvsr6b4) (no related file):*
Still need new icons for BYU Speeches and Transcripts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280#-KyXLqSWWZRteTmmWCSZ:-KyXMtECXF9-bVNfsmB3:bjg26r0) (no related file):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

Still need new icons for BYU Speeches and Transcripts
</blockquote></details>

Thanks for marking this. Sam will get these for you when she's in next

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280#-KybQko2vWZgnJ-cR-R8:-KybQko2vWZgnJ-cR-R9:b-5efcdh) (no related file):*
Get with Geoff and make sure they look the exact same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280)*

**Comment by romrell4** [comment]
Reviewed 5 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280)*

**Comment by romrell4** [comment]
Reviewed 48 of 48 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280)*

**Comment by alexanderboswell** [comment]
Review status: 25 of 34 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280#-KyXLqSWWZRteTmmWCSZ:-Kz9tYcYDlm8IyEoJ2RD:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Thanks for marking this. Sam will get these for you when she's in next
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280#-KybQko2vWZgnJ-cR-R8:-Kz9td52ZwRyWG71O8jy:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Get with Geoff and make sure they look the exact same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280)*

**Comment by romrell4** [comment]
Reviewed 10 of 13 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/280)*

**Pull request merged**
