### PR TITLE
Hotfix/cannon commons

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/189)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFilterViewController.h, line 11 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlI7AoS4FXWLgSu68t:-KmlI7AoS4FXWLgSu68u:b-swd3k3) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFilterViewController.h#L11)):*
> ```objc
> #import "ByuViewController.h"
> 
> @interface CannonCommonsFilterViewController : ByuViewController
> ```

Can we do this in swift?

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFilterViewController.m, line 57 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlJH0lVchkqySDAL6I:-KmlJH0lVchkqySDAL6J:b-gbbmni) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFilterViewController.m#L57)):*
> ```objc
>         [self.selectedAllergens addObject:self.allergens[indexPath.row]];
>     } else {
>         if ([self.selectedAllergens containsObject:self.allergens[indexPath.row]]) {
> ```

Do you need to check if it contains it? Will removeObject just do nothing if it doesn't exist?

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 13 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlNzbrQJ0M3E-Fb4Fk:-KmlNzbrQJ0M3E-Fb4Fl:b-2nnnqu) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L13)):*
> ```objc
> #import "CannonCommonsAllergenFilter.h"
> 
> @interface CannonCommonsFullMenuViewController () <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate>
> ```

I don't think you need to define UISearchBarDelegate here since you are already a ByuSearchableViewController

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 31 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlJz2r-RZMBuSPAz3H:-KmlJz2r-RZMBuSPAz3I:b-dcpltl) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L31)):*
> ```objc
>     
>     self.allergenFilteredMenu = [NSMutableDictionary dictionary];
>     [self applyAllergyFilters];
> ```

Why do you call it here if there is obviously nothing in the filtered menu?

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 43 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlKFZF2n85uAVAOkA3:-KmlKFZGZBlomzxKEVC5:b-52u4xe) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L43)):*
> ```objc
> }
> 
> -(void)allergenFilterCompleted:(NSNotification *)notification {
> ```

Call this `allergenFilterUpdated:` instead

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 51 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlKRSE-L1cAsDMd42P:-KmlKRSE-L1cAsDMd42Q:bdiyceg) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L51)):*
> ```objc
>     [self.allergenFilteredMenu removeAllObjects];
>     //Check each section in the menu
>     for (NSString *key in self.menu) {
> ```

Let's call this `station` instead of `key`

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 52 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlKmFgHUIL1PhnYtCc:-KmlKmFgHUIL1PhnYtCd:b-laj2r4) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L52)):*
> ```objc
>     //Check each section in the menu
>     for (NSString *key in self.menu) {
>         NSMutableArray<CannonCommonsRecipe *> *tempSection = [NSMutableArray array]; //A temp section to store all recipes that are not filtered out
> ```

Let's call this `filteredRecipes` instead of `tempSection`

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 57 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlLjWD_NklvUsdRcfd:-KmlLjWD_NklvUsdRcfe:b238usc) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L57)):*
> ```objc
>             BOOL noAllergens = YES;
>             //Check each allergen on the activeFilters list
>             for (NSString *allergen in [CannonCommonsAllergenFilter activeFilters]) {
> ```

We could do this with a set intersection

```objective-c
NSMutableSet *intersection = [NSMutableSet setWithArray:recipe.allergens];
[intersection intersectSet:[NSSet setWithArray:[CannonCommonsAllergenFilter activeFilters]]]; //We wouldn't have to create a set if we already saved the activeFilters as a set in the first place
if (intersection.count > 0) {
    [tempSection addObject:recipe];
}
```

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 97 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlNjMBmW61fXFEbWTU:-KmlNjMBmW61fXFEbWTV:b-9og55) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L97)):*
> ```objc
> 
> -(NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
>     return self.searchFilteredRecipes ? @"" : [NSString stringWithFormat:@"  %@", self.allergenFilteredMenu.allKeys[section]];
> ```

Return nil instead of @"", I think that will make the header go away entirely

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlOQgMTeDvnXTaCkKj:-KmlOQgMTeDvnXTaCkKk:b-h2a0na) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m#L16)):*
> ```objc
> 
> @property (weak, nonatomic) IBOutlet UITableView *tableView;
> @property (weak, nonatomic) IBOutlet UIView *footerView;
> ```

I don't think you need to save it. Just use self.tableView.footerView

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m, line 59 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlOht0gm3anMxvWOCf:-KmlOht0gm3anMxvWOCg:bo7g3vm) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m#L59)):*
> ```objc
> 
> -(void)applyAllergyFilters {
>     self.filteredRecipes = [@[] mutableCopy];
> ```

Haha- is this supposed to clear the recipes? Just use removeAllObjects instead

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m, line 62 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlOa8R4xl7QJ8OEfzj:-KmlOa8R4xl7QJ8OEfzk:b3virch) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m#L62)):*
> ```objc
>     //Check each recipe in the section
>     for (CannonCommonsRecipe *recipe in self.recipes) {
>         BOOL noAllergens = YES;
> ```

Can use set intersection. Also, since we're doing this in two places, we might want to move into something static that both can call

---

*[byuSuite/Apps/CannonCommons/model/CannonCommonsAllergenFilter.m, line 37 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlPht8XCSqnhbjwes3:-KmlPht8XCSqnhbjwes4:bi291ax) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/model/CannonCommonsAllergenFilter.m#L37)):*
> ```objc
> +(BOOL)setFilterWithAllergens:(NSArray<NSString *> *)allergens {
>     //Compare new allergens with old allergens to see if changes occurred
>     NSSet *set1 = [NSSet setWithArray:activeFilters];
> ```

You don't have to put them in sets to see if they are equal. You can use `isEqualToArray:`

---

*[byuSuite/Apps/CannonCommons/view/CannonCommonsFilterTableViewCell.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlQ7vFOPeMXAEDVizN:-KmlQ7vFOPeMXAEDVizO:bd8p20z) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/4b1176040253d4ae29de3e107dc6df119af6ac0e/byuSuite/Apps/CannonCommons/view/CannonCommonsFilterTableViewCell.swift#L20)):*
> ```Swift
>     }
>     
>     func setFilterSelection(selected: Bool) {
> ```

get a custom setter on filterOptionSelected instead

```objective-c
var filterOptionSelected: Bool = false {
  didSet {
    accessoryType = filterOptionSelected ? .checkmark : .none
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmmVQV4txPF_Q3kC7AD:-KmmVQV4txPF_Q3kC7AE:br93w3d) (no related file):*
Add a title to the top of the filter vc "Check an allergen to remove recipes with that allergen"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189)*

**Comment by ecbrady** [comment]
Review status: 12 of 13 files reviewed at latest revision, 15 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmmVQV4txPF_Q3kC7AD:-Kn1A7Qa9wR_dFhWh3qv:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add a title to the top of the filter vc "Check an allergen to remove recipes with that allergen"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189)*

**Comment by ecbrady** [comment]
Review status: 9 of 13 files reviewed at latest revision, 15 unresolved discussions.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFilterViewController.m, line 57 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlJH0lVchkqySDAL6I:-Kn1AtRchCN8BwsDcv5Q:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFilterViewController.m#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you need to check if it contains it? Will removeObject just do nothing if it doesn't exist?
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 13 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlNzbrQJ0M3E-Fb4Fk:-Kn1B17hDXneOyRBGAlA:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't think you need to define UISearchBarDelegate here since you are already a ByuSearchableViewController
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 31 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlJz2r-RZMBuSPAz3H:-Kn1B5oRUv9OpQL10D-B:b2lvwqj) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why do you call it here if there is obviously nothing in the filtered menu?
</blockquote></details>

There may be. If they set filters from the stations vc then switch to full menu I need to apply those filters her

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 43 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlKFZF2n85uAVAOkA3:-Kn1BMhYLDRl3YiLMXe1:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L43)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Call this `allergenFilterUpdated:` instead
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 51 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlKRSE-L1cAsDMd42P:-Kn1BTSs9XGupEsW_23F:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L51)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's call this `station` instead of `key`
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 52 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlKmFgHUIL1PhnYtCc:-Kn1BaRju9QY52Vo7POI:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's call this `filteredRecipes` instead of `tempSection`
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 97 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlNjMBmW61fXFEbWTU:-Kn1D-ESmzB-9E5mMHam:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L97)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Return nil instead of @"", I think that will make the header go away entirely
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlOQgMTeDvnXTaCkKj:-Kn1DmPM_YnoCD28Rr4E:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't think you need to save it. Just use self.tableView.footerView
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m, line 59 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlOht0gm3anMxvWOCf:-Kn1E1AOCplwVqYjaRaP:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m#L59)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Haha- is this supposed to clear the recipes? Just use removeAllObjects instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFilterViewController.h, line 11 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlI7AoS4FXWLgSu68t:-Kn4q-v7y6u9yYQhRwAx:b-ouuptc) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFilterViewController.h#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we do this in swift?
</blockquote></details>

I hope so. I was planning on converting it to swift when I converted everything else in my next project.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m, line 57 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlLjWD_NklvUsdRcfd:-Kn4uc6T3rHkwmq-d2rb:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsFullMenuViewController.m#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We could do this with a set intersection

```objective-c
NSMutableSet *intersection = [NSMutableSet setWithArray:recipe.allergens];
[intersection intersectSet:[NSSet setWithArray:[CannonCommonsAllergenFilter activeFilters]]]; //We wouldn't have to create a set if we already saved the activeFilters as a set in the first place
if (intersection.count > 0) {
    [tempSection addObject:recipe];
}
```
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m, line 62 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlOa8R4xl7QJ8OEfzj:-Kn4yI8vB57BVk2pURsm:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/controller/CannonCommonsMenuViewController.m#L62)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can use set intersection. Also, since we're doing this in two places, we might want to move into something static that both can call
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/model/CannonCommonsAllergenFilter.m, line 37 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlPht8XCSqnhbjwes3:-Kn4sPK8vAu20evwKAnD:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/model/CannonCommonsAllergenFilter.m#L37)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You don't have to put them in sets to see if they are equal. You can use `isEqualToArray:`
</blockquote></details>

Done.

---

*[byuSuite/Apps/CannonCommons/view/CannonCommonsFilterTableViewCell.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189#-KmlQ7vFOPeMXAEDVizN:-Kn4pq_8SA5mGiB5eJFw:b-150y1r) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/254906275679291e1d19d2048a5711d0fc1fc034/byuSuite/Apps/CannonCommons/view/CannonCommonsFilterTableViewCell.swift#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

get a custom setter on filterOptionSelected instead

```objective-c
var filterOptionSelected: Bool = false {
  didSet {
    accessoryType = filterOptionSelected ? .checkmark : .none
  }
}
```

</blockquote></details>

Like this? And then I don't need to set the accessoryType in the other two methods?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189)*

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/189)*

**Pull request merged**
