### PR TITLE
feature/printers -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/338)

### CODE REVIEW

**Comment by alexanderboswell** [comment]
Review status: 0 of 33 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBwE3xT0KI-S8ieWFQB:-LBwE3xT0KI-S8ieWFQC:b-3m1qqd) (no related file):*
BUG: Status bar is appearing white when the filter view controller is being presented. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/338)*

**Comment by romrell4** [comment]
Reviewed 28 of 33 files at r1.
Review status: 28 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBwE3xT0KI-S8ieWFQB:-LBzJmggC2AgzG_5rG4n:b-fjp3u3) (no related file):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

BUG: Status bar is appearing white when the filter view controller is being presented. 
</blockquote></details>

I know how to fix that one. Actually, Erik helped me fix that one. Check with him. You also may be able to mimic other features that have done it successfully. It's a little tricky though :-/

---

*[byuSuite/Apps/Printers/model/Printer.swift, line 66 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzKHaO8sHe0eh5zLx_:-LBzKHaO8sHe0eh5zLxa:bvhad2) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/model/Printer.swift#L66)):*
> ```Swift
> 	
> 	func hasRestrictions() -> Bool {
> 		if let restrictions = restrictions, restrictions != "" {
> ```

Could this be simplified to `return restrictions != ""`?

---

*[byuSuite/Apps/Printers/model/Printer.swift, line 74 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzKTgL4Byy44PPj7v-:-LBzKTgM-I-gHX246dug:b203cjf) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/model/Printer.swift#L74)):*
> ```Swift
> 	
> 	private func formattedFeatures() -> String {
> 		var features = [String]()
> ```

I think you can do this with a higher order function. See if you can think of how to do it

---

*[byuSuite/Apps/Printers/model/PrintersFilter.swift, line 19 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzKem75S7DCN6Zy_oq:-LBzKem75S7DCN6Zy_or:bda7gxe) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/model/PrintersFilter.swift#L19)):*
> ```Swift
> 
> 	static var activeFilters = [
> 		PRINTER_BLACK_WHITE_KEY : false,
> ```

Remove excess space

---

*[byuSuite/Apps/Printers/view/Printers.storyboard, line 312 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzKtbH94n8JKUf91f8:-LBzKtbH94n8JKUf91f9:b-su4kfq) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/view/Printers.storyboard#L312)):*
> ```XML
>                                                     <nil key="highlightedColor"/>
>                                                 </label>
>                                                 <stackView opaque="NO" contentMode="scaleAspectFit" semanticContentAttribute="forceLeftToRight" distribution="fillEqually" alignment="center" translatesAutoresizingMaskIntoConstraints="NO" id="UaS-dr-SI9">
> ```

Is this stack view replacing the crappy manual constraints that we had to set up?

---

*[byuSuite/Apps/Printers/view/PrintersTableViewCell.swift, line 24 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzL1nbES226vNPGAsX:-LBzL1nbES226vNPGAsY:b-dhq54u) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/view/PrintersTableViewCell.swift#L24)):*
> ```Swift
> 	var printer: Printer! {
> 		didSet {
> 				roomLabel.text = printer?.location
> ```

indentation issue?

---

*[byuSuite/Apps/Printers/view/PrintersTableViewCell.swift, line 25 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzL4ExBfSXG94bQ3ad:-LBzL4ExBfSXG94bQ3ae:bnki4z1) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/view/PrintersTableViewCell.swift#L25)):*
> ```Swift
> 		didSet {
> 				roomLabel.text = printer?.location
> 			if printer.hasRestrictions() {
> ```

Can hasRestrictions be a computed property rather than a func?

---

*[byuSuite/Apps/Printers/view/PrintersTableViewCell.swift, line 39 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzLKHwD97ZBCdPOVXU:-LBzLKHwD97ZBCdPOVXV:b-768unx) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/view/PrintersTableViewCell.swift#L39)):*
> ```Swift
> 		var numberOfOptions = 0
> 		
> 		if printer.blackWhite {
> ```

Can you think of a way of using a higher order function to do this? It might be a little more complicated, so we might not use it... but it's good to think about when you have logic repeating like this

---

*[byuSuite/Apps/Printers/view/PrintersTableViewCell.swift, line 60 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzLX_Y87eE836k4jR-:-LBzLX_Y87eE836k4jR0:bh3eaq0) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/view/PrintersTableViewCell.swift#L60)):*
> ```Swift
> 		}
> 		
> 		stackViewWidth.constant = CGFloat(IMAGE_WIDTH * numberOfOptions + STACK_VIEW_SPACING * (numberOfOptions - 1))
> ```

Don't stack views do this automatically?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/338)*

**Comment by romrell4** [comment]
Reviewed 5 of 33 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[byuSuite/Apps/Printers/controller/PrintersBuildingDetailViewController.swift, line 38 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC--nb07BKtZbdG5tcp:-LC--nb07BKtZbdG5tcq:b-3yuzgu) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersBuildingDetailViewController.swift#L38)):*
> ```Swift
> 	override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
> 		if let printer: Printer = tableData.object(forIndexPath: indexPath), printer.hasRestrictions() {
> 			ViewUtils.createSimplePopup(from: self, title: "Restrictions", message: printer.restrictions, callback: { (_) in
> ```

No ViewUtils

---

*[byuSuite/Apps/Printers/controller/PrintersBuildingsViewController.swift, line 23 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzxMnJ4r2jHYzHTUdI:-LBzxMnJ4r2jHYzHTUdJ:ba3u4be) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersBuildingsViewController.swift#L23)):*
> ```Swift
> 		loadData()
> 		
> 		NotificationCenter.default.addObserver(self, selector: #selector(loadData), name: PRINTER_FILTER_NOTIFICATION, object: nil)
> ```

Can you think of a way of doing this with unwind segues instead of notifications?

---

*[byuSuite/Apps/Printers/controller/PrintersBuildingsViewController.swift, line 38 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzxXew7u7kg6yP2X6w:-LBzxXex5B7ib_vQUkbe:bj785z9) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersBuildingsViewController.swift#L38)):*
> ```Swift
> 	
> 	override func getFilteredPredicate(searchText: String) -> ((Row) -> Bool) {
> 		//TODO: Remove when restrooms is merged, this is the default behavior now
> ```

Do it (leave open until resolved)

---

*[byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift, line 22 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC-0DxgA8lX7HsMiqNF:-LC-0Dxh5c_XUcQfvgcD:bspdj5t) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift#L22)):*
> ```Swift
>         super.viewDidLoad()
> 		
> 		tableData = TableData(rows: [
> ```

I'm thinking of a way to simplify this statement... What do you think of something like this:
```swift
		tableData = TableData(rows: [
			("Black & White", "blackWhite", PRINTER_BLACK_WHITE_KEY),
			("Color", "color", PRINTER_COLOR_KEY),
			("Double-Sided", "duplex", PRINTER_DUPLEX_KEY)
		].map { Row(text: $0.0, moreInfo: [IMAGE_NAME_KEY: $0.1, FILTER_KEY: $0.2, FILTER_OPTION_CHANGED_KEY: PrintersFilter.activeFilters[$0.2] ?? false]) })
```

---

*[byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift, line 25 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC-1XSC8K3wjLVuxDYR:-LC-1XSC8K3wjLVuxDYS:b82kyw3) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift#L25)):*
> ```Swift
> 			Row(text: "Black & White", moreInfo: [IMAGE_NAME_KEY: "blackWhite", FILTER_KEY: PRINTER_BLACK_WHITE_KEY, FILTER_OPTION_CHANGED_KEY: PrintersFilter.activeFilters[PRINTER_BLACK_WHITE_KEY] ?? false]),
> 			Row(text: "Color", moreInfo: [IMAGE_NAME_KEY: "color", FILTER_KEY: PRINTER_COLOR_KEY, FILTER_OPTION_CHANGED_KEY: PrintersFilter.activeFilters[PRINTER_COLOR_KEY] ?? false]),
> 			Row(text: "Double-Sided", moreInfo: [IMAGE_NAME_KEY: "print_duplex", FILTER_KEY: PRINTER_DUPLEX_KEY, FILTER_OPTION_CHANGED_KEY: PrintersFilter.activeFilters[PRINTER_DUPLEX_KEY] ?? false])
> ```

make `print_duplex` camel cased (or just name it `duplex` instead)

---

*[byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift, line 36 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC-2PUTBg7hVohouyKq:-LC-2PUTBg7hVohouyKr:b-eqit7e) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift#L36)):*
> ```Swift
> 			return UITableViewCell()
> 		}
> 		cell.filterLabel.text = row.text
> ```

Add newline above this line and remove other excess newlines in the function

---

*[byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift, line 48 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC-2XTX6eTHDovSpBQr:-LC-2XTX6eTHDovSpBQs:b-89817p) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift#L48)):*
> ```Swift
> 		let row = tableData.row(forIndexPath: indexPath)
> 		if var moreInfo = row.moreInfo, let filterOptionChanged = moreInfo[FILTER_OPTION_CHANGED_KEY] as? Bool {
> 			//todo: get actual reference to row moreInfo to get rid of !.
> ```

Do it

---

*[byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift, line 63 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC-2ffx7USd2ztIZmC5:-LC-2ffx7USd2ztIZmC6:b-u0bhgm) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift#L63)):*
> ```Swift
> 		
> 		if filtersChanged() {
> 			NotificationCenter.default.post(name: PRINTER_FILTER_NOTIFICATION, object: nil)
> ```

unwind possible here?

---

*[byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift, line 76 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC-3HEe-LRP4A1ZnTDe:-LC-3HEe-LRP4A1ZnTDf:b-io09l7) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift#L76)):*
> ```Swift
> 		var filterByDuplex = false
> 
> 		for row in tableData.rows() {
> ```

I think this could be a map (assuming that there are only three rows in the tabledata...) Thoughts? Here is what the result might look like:
```swift
	private func filtersChanged() -> Bool {
		let filters = tableData.rows().map { $0.moreInfo?[FILTER_OPTION_CHANGED_KEY] as? Bool ?? false }
		return PrintersFilter.updatedFilters(blackWhite: filters[0], color: filters[1], duplex: filters[2])
	}
```

---

*[byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift, line 88 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC-2oaq5n8s1TOGu5ct:-LC-2oar2PgtiFzTx03D:b-5zijfq) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersFilterViewController.swift#L88)):*
> ```Swift
> 		}
> 		
> 		return PrintersFilter.updatedFilters(blackWhite: filterByBlackWhite, color: filterByColor, duplex: filterByDuplex)
> ```

Should this function be called `updateFilters` instead of `updatedFilters`?

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.swift, line 19 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzy0GuDUMw3hiqG39f:-LBzy0GuDUMw3hiqG39g:b-5unk55) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersMapViewController.swift#L19)):*
> ```Swift
> 	//MARK: Private Variables
> 	
> 	private var locationManager = CLLocationManager()
> ```

Do we need a location manager here? if it's just for the dot on the map, remove

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.swift, line 39 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzyD7xBv5FwChHvdHR:-LBzyD7xBv5FwChHvdHS:b4qnoai) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersMapViewController.swift#L39)):*
> ```Swift
> 	func mapView(_ mapView: MKMapView, annotationView view: MKAnnotationView, calloutAccessoryControlTapped control: UIControl) {
> 		if let printer = view.annotation as? Printer {
> 			ViewUtils.createSimplePopup(from: self, title: "Restrictions", message: printer.restrictions)
> ```

Whoa! I thought we deleted this already! Just use the showDialog() already on the ViewController class. See how many people are still using ViewUtils (it should be deleted)

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.swift, line 45 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzyUbT6mxqOFt0snPp:-LBzyUbT6mxqOFt0snPq:biimv5v) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersMapViewController.swift#L45)):*
> ```Swift
> 	func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
> 		//If it is kind of MKUserLocation then return nil so it will default to displaying a blue dot.
> 		if annotation.isKind(of: MKUserLocation.self) {
> ```

one line `guard` instead

And check with Erik... I think one of the branch we're working on is going to simplify this. I think it's `mapView.defaultSomethingOrOther()`

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.swift, line 48 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzytvD2sdruv3q9FUR:-LBzytvD2sdruv3q9FUS:b-ey58g7) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersMapViewController.swift#L48)):*
> ```Swift
> 			return nil
> 		} else if let printer = annotation as? Printer {
> 			let pinView = MKPinAnnotationView(annotation: annotation)
> ```

We need to be dequeuing a reusable pin. The above comment should take care of that

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.swift, line 52 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzyypp-lNW6uJKlr21:-LBzyypp-lNW6uJKlr22:bvckl7y) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersMapViewController.swift#L52)):*
> ```Swift
> 			if printer.hasRestrictions() {
> 				pinView.rightCalloutAccessoryView = UIButton(type: .detailDisclosure)
> 			}
> ```

This may need an else once we start recycling (otherwise, the rightCalloutAccessoryView might be set from the last recycled one)

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.swift, line 61 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzxxfR1qLxHTN_bfHl:-LBzxxfR1qLxHTN_bfHm:b69sg7i) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersMapViewController.swift#L61)):*
> ```Swift
> 	
> 	func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
> 		locationManager.startUpdatingLocation()
> ```

Why do we start updating locations every time we update?

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.swift, line 68 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzzEH2-CxNPq9nDNXs:-LBzzEH2-CxNPq9nDNXt:bky05tw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/controller/PrintersMapViewController.swift#L68)):*
> ```Swift
> 	@objc func loadData() {
> 		spinner.startAnimating()
> 		mapView.removeAnnotations(mapView.annotations)
> ```

Does this mean that it removes the old annotations while the new ones are loading? Is this the desired behavior?

---

*[byuSuite/Apps/Printers/model/PrintersClient.swift, line 17 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LBzzSKJ6aJuf2Lhv04b:-LBzzSKJ6aJuf2Lhv04c:b890kp5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/model/PrintersClient.swift#L17)):*
> ```Swift
> 	static func getAllBuildingsWithCurrentFilter(callback: @escaping([PrintersBuilding]?, ByuError?) -> Void) {
> 		let request = ByuRequest2(url: super.url(base:BASE_URL, pathParams: ["buildings"], queryParams: getFilterParams()))
> 		ByuRequestManager.instance.makeRequest(request) { (response) in
> ```

I'm starting to wonder if we could put `ByuRequestManager.instance.makeRequest` into the ByuClient2 as `makeRequest`. I think we only ever call this from ByuClient's... Maybe we could even combine the logic for creating the request... Talk to me about this if you don't understand

---

*[byuSuite/Apps/Printers/model/PrintersClient.swift, line 58 at r1](https://reviewable.io/reviews/byu-oit/ios-byusuite/338#-LC--Ey-CuorhdjI_pKP:-LC--Ey-CuorhdjI_pKQ:bmmfz78) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/3b6963cf257ba7d2264d3520213dbb6b74761180/byuSuite/Apps/Printers/model/PrintersClient.swift#L58)):*
> ```Swift
> 			
> 			return [
> 				"blackWhite": String(blackWhite),
> ```

This could be simplified by making a String init? function that takes in a boolean and returns nil. Then we wouldn't need the if/let (thereby removing the duplicate keys)

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/338)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 28 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/338)*

**Pull request merged**
