### PR TITLE
feature/testingCenter -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/314)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[byuSuite/Classes/Reusable/Clients/CampusCameraClient.swift, line 17 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z4B4_8jpQ9ekK_7OC:-L7z4B4_8jpQ9ekK_7OD:b-5ugov6) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/Clients/CampusCameraClient.swift#L17)):*
> ```Swift
>             if response.succeeded, let responseArray = response.getDataJson() as? [[String: Any]] {
> 				do {
>                 let streams = try responseArray.map{ try CameraStream(dict: $0) }
> ```

Is this indented properly?

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 11 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z5cn-9GoiZD3DQXAc:-L7z5cn-9GoiZD3DQXAd:bwjamu3) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L11)):*
> ```Swift
> import UIKit
> 
> class CameraCell: UICollectionViewCell {
> ```

Could we get some extra comments in this code? We did some out-of-the-box things that could be difficult to maintain if we don't have really good comments

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 13 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z4JoL5yPxszIMpgiN:-L7z4JoL5yPxszIMpgiO:bh0mc69) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L13)):*
> ```Swift
> class CameraCell: UICollectionViewCell {
> 	//MARK: Outlets
> 	@IBOutlet weak var imageView: UIImageView!
> ```

private?

---

*[byuSuite/Classes/Reusable/UI/Cameras/Cameras.storyboard, line 127 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z67h8Alzdu2Nu1EGc:-L7z67h8Alzdu2Nu1EGd:bkbu0um) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/Cameras.storyboard#L127)):*
> ```XML
>                         <viewLayoutGuide key="safeArea" id="dyY-Xn-KoC"/>
>                     </view>
>                     <tabBarItem key="tabBarItem" title="Testing Center Lines" image="cameraIcon.png" id="IzA-XP-hZW"/>
> ```

It looks like there's still a tab bar item here... Is that intended?

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 11 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z6Fue9KqfwbAJAIGV:-L7z6Fue9KqfwbAJAIGW:bqv93sy) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L11)):*
> ```Swift
> import UIKit
> 
> private let MIN_INTERVAL = 15   //Some streams have a 1 sec refresh which doesn't make sense on a mobile device.
> ```

You can remove this now that we updated the web service to only have 15 sec intervals

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 34 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z6M71BSYz-MWSWjAo:-L7z6M71BSYz-MWSWjAp:b-t7esza) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L34)):*
> ```Swift
> 
> 	var notificationName: NSNotification.Name {
> 		return NSNotification.Name("LOADED-\(streamId)")
> ```

Make this CAMERA_LOADED-<streamId>

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 81 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z6ebF7yFuRb0xawpd:-L7z6ebF7yFuRb0xawpe:b-xhxpi9) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L81)):*
> ```Swift
> 					self.image = image
> 				} else {
> 					//TODO: error, what should happen though?
> ```

Resolve TODO

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 57 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z78VvB8D7FAW6jV-w:-L7z78VvB8D7FAW6jV-x:b-mwxm2w) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L57)):*
> ```Swift
> 		}
> 		
> 		if filter != nil {
> ```

This sort of logic makes me wonder if we should be using a subclass rather than reusing the same class... Thoughts?

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 73 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z7FuVDpLyksO5q9CZ:-L7z7FuVDpLyksO5q9C_:b2fiewc) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L73)):*
> ```Swift
> 	// MARK: UICollectionViewDataSource
> 	
> 	func numberOfSections(in collectionView: UICollectionView) -> Int {
> ```

Is this not default? Can you remove this function?

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 82 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z7MgoC9m5Vrua0Van:-L7z7MgoC9m5Vrua0Vao:b-aj6c5l) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L82)):*
> ```Swift
> 	
> 	func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
> 		guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as? CameraCell else {
> ```

Add this to extensions (like we have for tableView.dequeue....)

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 124 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z9T2HCyV9ZavKkt7d:-L7z9T2HCyV9ZavKkt7e:b-np0a6u) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L124)):*
> ```Swift
> 		// Save the location of the cell so we can put it back to the right locatiom
> 		cellLocation = cell.layer.position
> 		UIView.animate(withDuration: 0.3, delay: 0, options: .curveEaseOut, animations: {
> ```

Move animation duration to private let (here and below)

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 124 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7zAVhpAEEbW2qeBYJf:-L7zAVhpAEEbW2qeBYJg:bxvvke8) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L124)):*
> ```Swift
> 		// Save the location of the cell so we can put it back to the right locatiom
> 		cellLocation = cell.layer.position
> 		UIView.animate(withDuration: 0.3, delay: 0, options: .curveEaseOut, animations: {
> ```

Can we use trailing closure syntax? (here and below)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[byuSuite/Classes/Reusable/Clients/CampusCameraClient.swift, line 17 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z4B4_8jpQ9ekK_7OC:-L87xtG0-zUWkuWGWRDq:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/Clients/CampusCameraClient.swift#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this indented properly?
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 11 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z5cn-9GoiZD3DQXAc:-L88S9zU0QDAtKGqfp-r:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could we get some extra comments in this code? We did some out-of-the-box things that could be difficult to maintain if we don't have really good comments
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 13 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z4JoL5yPxszIMpgiN:-L88SAHl5nvomWByhgJO:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

private?
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/Cameras.storyboard, line 127 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z67h8Alzdu2Nu1EGc:-L88TcryEeQeIvlPcOA9:bt17yvd) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/Cameras.storyboard#L127)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It looks like there's still a tab bar item here... Is that intended?
</blockquote></details>

Yes, this tab bar item is needed here or it will not appear in the tab bar of the testing center feature. By default though, because it is not inside of a tab bar in this storyboard, it will not appear.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 11 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z6Fue9KqfwbAJAIGV:-L88UY3-4PYkzA0pLsMj:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can remove this now that we updated the web service to only have 15 sec intervals
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 34 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z6M71BSYz-MWSWjAo:-L88Ua2p2O7yxWgxRAcD:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make this CAMERA_LOADED-<streamId>
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 81 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z6ebF7yFuRb0xawpd:-L88_3R73FFsWzyA3hjO:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L81)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Resolve TODO
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 57 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z78VvB8D7FAW6jV-w:-L88WmSN2YLPyinNafkM:b-e5w0v7) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This sort of logic makes me wonder if we should be using a subclass rather than reusing the same class... Thoughts?
</blockquote></details>

I would say that is something that should be done if we have a third feature that will use cameras, but I think for now that it would be extra code setup for the unlikely possibility of another feature ever using it.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 73 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z7FuVDpLyksO5q9CZ:-L88UwwZAybvv7M33wMu:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this not default? Can you remove this function?
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 82 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z7MgoC9m5Vrua0Van:-L88Wf_CAfZt1teJePKG:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L82)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add this to extensions (like we have for tableView.dequeue....)
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 124 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7z9T2HCyV9ZavKkt7d:-L88VREd-sTWhvGiS2u1:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L124)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move animation duration to private let (here and below)
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 124 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L7zAVhpAEEbW2qeBYJf:-L88Xf446RC42oEMVdfq:b-hiq6hi) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/695b7b83b58264858b5ac316e239ac652fc18bf7/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L124)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we use trailing closure syntax? (here and below)
</blockquote></details>

No we are not able to, we tried this the other day but with the options we want it is not possible to do trailing closure syntax.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314)*

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 48 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L8DPPhG8WqJ463H3PoF:-L8DPPhG8WqJ463H3PoG:b-5p0jol) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L48)):*
> ```Swift
> 		self.center = center
> 		if zoomIn {
> 			self.transform = CGAffineTransform(scaleX: 2, y: 2)
> ```

Comment about why we chose 2x for scaling

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 56 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L8DPUb5BrkVBPut6C0d:-L8DPUb5BrkVBPut6C0e:bglpout) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L56)):*
> ```Swift
> 			*/
> 			if let height = cameraStream.image?.size.height, let width = cameraStream.image?.size.width {
> 				infoViewBottomConstraint.constant = (self.frame.size.height - self.frame.size.width * (height / width)) / 4
> ```

Did we ever figure out the divide by 4 mystery?

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 59 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L8DPaDrA15YrpdmtL2q:-L8DPaDrA15YrpdmtL2r:b15ni32) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L59)):*
> ```Swift
> 			}
> 		} else {
> 			infoViewBottomConstraint.constant = 0
> ```

Let's move this to the bottom (so that it's the same order as in the `if` above)

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 74 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L8DOltfELKBxVUZ97JQ:-L8DOltfELKBxVUZ97JR:bb7phvt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L74)):*
> ```Swift
> 					self.image = image
> 				}
> 				//If there is an error then it will just keep the preivous image and reset the timer.
> ```

typo

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 84 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L8DOw8RAa2KH-1EUG4y:-L8DOw8RAa2KH-1EUG4z:b-b8fylh) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L84)):*
> ```Swift
> 		savedTimeInterval = Double(refreshInterval)
> 		resumeTimer()
> 		NotificationCenter.default.post(name: notificationName, object: nil)
> ```

What is this notification doing? Add a comment

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 117 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L8DPG--D5cNvyNvH7WS:-L8DPG-0-Y19Yi5TXMAP:b-us82tn) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L117)):*
> ```Swift
> 		visualEffectView.isUserInteractionEnabled = true
> 		// Save the location of the cell so we can put it back to the right locatiom
> 		cellLocation = cell.layer.position
> ```

Do we need to save this separately? Or can we compute this based on the selected cell (which is set above)?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 48 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/314#-L8DPPhG8WqJ463H3PoF:-L8IGtlGiXhL6yoZsEHY:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L48)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about why we chose 2x for scaling
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 56 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/314#-L8DPUb5BrkVBPut6C0d:-L8IL-P2tdxRFLASEiWI:b4vmjtr) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L56)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Did we ever figure out the divide by 4 mystery?
</blockquote></details>

Not quiet sure, it is still have the value that I thought it needed to be. But this is thinking that we know how the .scaleAspectFit is really working (because we dont actually know how big the image is, just the ratio compared to the width).

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 59 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/314#-L8DPaDrA15YrpdmtL2q:-L8IGzxhpURvDYraTZN5:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L59)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's move this to the bottom (so that it's the same order as in the `if` above)
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 74 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/314#-L8DOltfELKBxVUZ97JQ:-L8IHHNN9t0BbnUn2XMs:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L74)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift, line 84 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/314#-L8DOw8RAa2KH-1EUG4y:-L8IHW7i4lXI42lozpAC:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraStream.swift#L84)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this notification doing? Add a comment
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift, line 117 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/314#-L8DPG--D5cNvyNvH7WS:-L8II8WDtANGdmrGPWFe:bg54y7g) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CamerasViewController.swift#L117)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need to save this separately? Or can we compute this based on the selected cell (which is set above)?
</blockquote></details>

We have to save it separately as when we zoom in on a camera we are changing its position. And the cell we are moving is the selected cell, as it keeps a reference to the cell and is not a copy of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/314)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 56 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314#-L8DPUb5BrkVBPut6C0d:-L8INJdFAdyxcLUy9s72:b-3vuwvj) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/9a483a60f4745fe96402a4ebebdc9cbe16732baf/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L56)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

Not quiet sure, it is still have the value that I thought it needed to be. But this is thinking that we know how the .scaleAspectFit is really working (because we dont actually know how big the image is, just the ratio compared to the width).
</blockquote></details>

Interesting. Let's keep looking into it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/314)*

**Pull request merged**
