### PR TITLE
feature/idCard -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/293)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 11 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlQs87KuTyJwyebis:-L0tlQs87KuTyJwyebit:b-x2j720) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L11)):*
> ```Swift
> import UIKit
> 
> class IDCardViewController: UIViewController {
> ```

Definitely use ByuViewController

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 15 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlSyBCbAGbWZZtrCK:-L0tlSyBCbAGbWZZtrCL:buc3kym) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L15)):*
> ```Swift
> 	//MARK: Private variables
> 	
> 	var callbackCounter = 0
> ```

private

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 19 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlTm766OCUH6YJiPT:-L0tlTm766OCUH6YJiPU:b-8w7klk) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L19)):*
> ```Swift
> 	//MARK: Control Outlets
> 	
> 	@IBOutlet weak var personImageView: UIImageView!
> ```

private on all of these

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlWQ0Tq4Y0Y-SM_lN:-L0tlWQ0Tq4Y0Y-SM_lO:b-8w7klk) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L30)):*
> ```Swift
> 	//MARK: Constraint Outlets
> 	
> 	@IBOutlet weak var cardImgViewLeading: NSLayoutConstraint!
> ```

private on all of these

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 98 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlkiKhzk9Tvt7GTEe:-L0tlkiKhzk9Tvt7GTEf:b-bmxt5b) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L98)):*
> ```Swift
> 			self.stopAnimatingSpinnerIfReady()
> 			if let idCard = idCard {
> 				var backgroundImageName = "idCardDefault.png"
> ```

private lets at the top for all of these

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 119 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tluucCWKWBr1ZnqAo:-L0tluucCWKWBr1ZnqAp:bcvtopr) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L119)):*
> ```Swift
> 				
> 			} else {
> 				self.displayAlert(error: error)
> ```

Just curious... If both of these calls fail, what would happen? Would it try to display two alerts? Would that break? Would there be a warning in the logs? Do we need something that will only display an alert if there isn't one already displaying?

---

*[byuSuite/Apps/IDCard/Model/IDCard.swift, line 17 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmCXyx2pTr7gRLyVZ:-L0tmCXyx2pTr7gRLyV_:brfc60x) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/Model/IDCard.swift#L17)):*
> ```Swift
> 	var byuId: String?
> 	var issueNumber: String?
> 	var dtf = false 				//stands for Disaster Task Force
> ```

Don't default them here. `var dtf: Bool`

---

*[byuSuite/Apps/IDCard/Model/IDCardClient.swift, line 27 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmapd82ukhsp9ReEI:-L0tmapekqBC-YACUa4g:b-2kqof7) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/Model/IDCardClient.swift#L27)):*
> ```Swift
> 				})
> 			} else {
> 				callback(nil, ByuError(readableMessage: "Failed to load personal information"))
> ```

Do we throw this same error many places when we are dealing with nil personSummaries? If so, let's save the ByuError as a public static var in the PersonSummary or something

---

*[byuSuite/Apps/IDCard/view/IDCard.storyboard, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmoidhGKE4TZvAglB:-L0tmoidhGKE4TZvAglC:brl7yvq) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/view/IDCard.storyboard#L30)):*
> ```XML
>                         <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
>                         <subviews>
>                             <imageView userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" misplaced="YES" image="idCardDefault.png" translatesAutoresizingMaskIntoConstraints="NO" id="te7-el-BYg">
> ```

Misplaced? Do you know what that means? Does your storyboard have warnings?

---

*[byuSuite/Apps/IDCard/view/IDCard.storyboard, line 77 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmtpFfRGL8PVImkM0:-L0tmtpFfRGL8PVImkM1:b-34vmyd) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/view/IDCard.storyboard#L77)):*
> ```XML
>                                 <nil key="highlightedColor"/>
>                             </label>
>                             <activityIndicatorView opaque="NO" contentMode="scaleToFill" horizontalHuggingPriority="750" verticalHuggingPriority="750" misplaced="YES" hidesWhenStopped="YES" animating="YES" style="gray" translatesAutoresizingMaskIntoConstraints="NO" id="6sX-Yv-RXa">
> ```

See above

---

*[byuSuite/Classes/Reusable/Clients/PersonPhotoClient2.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tn3F2gZskzQvrTtqG:-L0tn3F2gZskzQvrTtqH:bmq40bf) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Classes/Reusable/Clients/PersonPhotoClient2.swift#L16)):*
> ```Swift
> 			if let personSummary = personSummary {
> 				let request = ByuRequest2(url: super.url(base: BASE_URL, queryParams: ["p": personSummary.personId]))
> 				request.authMethod = .OAUTH
> ```

Remove. That should be default...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 11 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlQs87KuTyJwyebis:-L0trS8-kZaCBfj1ZLMo:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Definitely use ByuViewController
</blockquote></details>

Done.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 15 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlSyBCbAGbWZZtrCK:-L0tsiKE0Ck0gTx72TVT:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

private
</blockquote></details>

Done.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 19 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlTm766OCUH6YJiPT:-L0tsjXfdKOCj4tkKYjo:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

private on all of these
</blockquote></details>

Done.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlWQ0Tq4Y0Y-SM_lN:-L0tskRqfcohYnQZVylX:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L30)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

private on all of these
</blockquote></details>

Done.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 98 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tlkiKhzk9Tvt7GTEe:-L0ttRe25JhW3kc-0uPS:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L98)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

private lets at the top for all of these
</blockquote></details>

Done.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 119 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tluucCWKWBr1ZnqAo:-L0tuqdhm6TpI5j67AXB:bncxu8b) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L119)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Just curious... If both of these calls fail, what would happen? Would it try to display two alerts? Would that break? Would there be a warning in the logs? Do we need something that will only display an alert if there isn't one already displaying?
</blockquote></details>

Im not sure, I was following the logic of what was implemented last. 

---

*[byuSuite/Apps/IDCard/Model/IDCard.swift, line 17 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmCXyx2pTr7gRLyVZ:-L0tu9lqXvH9vVdbGIR6:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/Model/IDCard.swift#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't default them here. `var dtf: Bool`
</blockquote></details>

Done.

---

*[byuSuite/Apps/IDCard/view/IDCard.storyboard, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmoidhGKE4TZvAglB:-L0tuh_7Gdf3CaqH3ycX:b3l1in1) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/view/IDCard.storyboard#L30)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Misplaced? Do you know what that means? Does your storyboard have warnings?
</blockquote></details>

Not sure, but what I have found online looks like its an xcode bug. 

---

*[byuSuite/Classes/Reusable/Clients/PersonPhotoClient2.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tn3F2gZskzQvrTtqG:-L0trNDRvpGPFiVZtuyd:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Classes/Reusable/Clients/PersonPhotoClient2.swift#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove. That should be default...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 119 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tluucCWKWBr1ZnqAo:-L0uAvuFxzPnBuHN8KTd:biua44a) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L119)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

Im not sure, I was following the logic of what was implemented last. 
</blockquote></details>

Totally. I just mean look into it. See what happens

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/IDCard/view/IDCard.storyboard, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmoidhGKE4TZvAglB:-L0uBY2Zgm2_SzTuaBr0:bi6c1ww) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/view/IDCard.storyboard#L30)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

Not sure, but what I have found online looks like its an xcode bug. 
</blockquote></details>

Interesting... But it doesn't cause issues in the interface builder? No yellow warnings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/IDCard/view/IDCard.storyboard, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmoidhGKE4TZvAglB:-L0uBfNbSAcdoJ-9zieR:b51721a) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/view/IDCard.storyboard#L30)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Interesting... But it doesn't cause issues in the interface builder? No yellow warnings?
</blockquote></details>

No yellow warnings, I can try changing the source of the storyboard and play around with it a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 119 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tluucCWKWBr1ZnqAo:-L0uGr7g7MsCTxktfhJA:b-gyrlgc) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L119)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Totally. I just mean look into it. See what happens
</blockquote></details>

It only displays once. In the console you can see a warning, "attempting to present UIAlertController on IDCardViewController which is already presenting". 

---

*[byuSuite/Apps/IDCard/Model/IDCardClient.swift, line 27 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmapd82ukhsp9ReEI:-L0uFYQtEb_e5opghuag:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/Model/IDCardClient.swift#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we throw this same error many places when we are dealing with nil personSummaries? If so, let's save the ByuError as a public static var in the PersonSummary or something
</blockquote></details>

Done.

---

*[byuSuite/Apps/IDCard/view/IDCard.storyboard, line 30 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tmoidhGKE4TZvAglB:-L0uGGa2dZ44UkxBO0L8:be4jhyk) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/view/IDCard.storyboard#L30)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

No yellow warnings, I can try changing the source of the storyboard and play around with it a bit.
</blockquote></details>

Removed from storyboard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 119 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tluucCWKWBr1ZnqAo:-L0zEPVMGsdrql8Krjes:bbyxdfb) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L119)):*
<details><summary><i>Previously, alexanderboswell (Alexander Boswell) wrote…</i></summary><blockquote>

It only displays once. In the console you can see a warning, "attempting to present UIAlertController on IDCardViewController which is already presenting". 
</blockquote></details>

Ah. Try to come up with something in the showAlert that will check if something is already displaying before presenting itself

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.swift, line 119 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L0tluucCWKWBr1ZnqAo:-L1wvzl_w6KSpItwnJRc:bkrpioc) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/78732f07c59adcfd1f917f727fd4e8e1fb1c2a77/byuSuite/Apps/IDCard/controller/IDCardViewController.swift#L119)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Ah. Try to come up with something in the showAlert that will check if something is already displaying before presenting itself
</blockquote></details>

Done. Check in extension to prevent warning. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L1wz1IpJgxhFmilxv1Z:-L1wz1IpJgxhFmilxv1_:btohg8e) (no related file):*
Let's get this tested with users from the service desk. I want to make sure it's working with more people before releasing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293#-L1wz1IpJgxhFmilxv1Z:-L1x3G4sd_4ZYGdrKmnp:b-c0rmre) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's get this tested with users from the service desk. I want to make sure it's working with more people before releasing
</blockquote></details>

Worked for a few users from the service desk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/293)*

**Pull request merged**
