### PR TITLE
Hotfix/campus operator

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/194)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 22 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnaiqTRc48JyyurJHRB:-KnaiqTRc48JyyurJHRC:b7ujzxn) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L22)):*
> ```Swift
>         
>         var rows = [Row]()
>         if UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiom.phone {
> ```

Don't worry about this if. Go ahead and show them all the options up front

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 33 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajLQOP2e2epxMEBW-:-KnajLQPNYdM72q2u8jq:b6y7b4b) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L33)):*
> ```Swift
>                     messageController.messageComposeDelegate = self
>                     messageController.recipients = [BYU_INFO_NUMBER]
>                     messageController.body = ""
> ```

I think this may be the default... Try removing it

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 60 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajXJqKgPsK6zoCi32:-KnajXJqKgPsK6zoCi33:bljxjf3) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L60)):*
> ```Swift
>         super.viewWillAppear(animated)
>         
>         if let indexPath = tableView.indexPathForSelectedRow {
> ```

This may not work for some of the options... See if coming back to the app from your phone or email actually deselects the row properly

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 68 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-Knajg6-0jqtJtR8YVhL:-Knajg6-0jqtJtR8YVhM:b-gcztz5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L68)):*
> ```Swift
>     
>     func tableView(_ tableView: UITableView, titleForFooterInSection section: Int) -> String? {
>         return section == 0 ? "Campus operators can help you find phone numbers, information about BYU activities, and other related university information." : ""
> ```

Isn't there only one section? if so, don't worry about the ternary

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 84 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajtBhvStgVJYqoJMe:-KnajtBhvStgVJYqoJMf:b-aoospw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L84)):*
> ```Swift
>     func mailComposeController(_ controller: MFMailComposeViewController, didFinishWith result: MFMailComposeResult, error: Error?) {
>         if result == MFMailComposeResult.failed {
>             super.displayAlert(error: nil, title: "Error", message: "your email failed to send. Please try again later.")
> ```

Capitalize "your"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 22 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnaiqTRc48JyyurJHRB:-Kne5Juxw28JvMJSk_-D:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't worry about this if. Go ahead and show them all the options up front
</blockquote></details>

Done.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 33 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajLQOP2e2epxMEBW-:-Kne5W4BCA06usvdES-P:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think this may be the default... Try removing it
</blockquote></details>

Done.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 60 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajXJqKgPsK6zoCi32:-Kne4eiZ-s6q6gPbZ5hG:b-nv3mse) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L60)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This may not work for some of the options... See if coming back to the app from your phone or email actually deselects the row properly
</blockquote></details>

It does work except on phones like my test phone that block calling because it doesn't actually open another view. 

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 68 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-Knajg6-0jqtJtR8YVhL:-Kne4qGvwzFO57pm_ixz:b-5u93ac) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Isn't there only one section? if so, don't worry about the ternary
</blockquote></details>

Okay. I was just duplicating the logic from the original.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 84 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajtBhvStgVJYqoJMe:-Kne59nTP1vZbIhbZ8eE:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L84)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Capitalize "your"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 60 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajXJqKgPsK6zoCi32:-KneFD7jzigW9L32CGGN:bbbusn6) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L60)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

It does work except on phones like my test phone that block calling because it doesn't actually open another view. 
</blockquote></details>

Yup. That's what I thought. So let's just remove this and do it in the didSelectRow method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 60 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajXJqKgPsK6zoCi32:-KneK1t7C7U8eBCZiCA6:b-nlc1cv) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L60)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yup. That's what I thought. So let's just remove this and do it in the didSelectRow method
</blockquote></details>

Did selectRow is being handled by TableData though. Do we want to duplicate that logic here and override TableData or do we want to add a deselectRow to TableData's didSelect?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 60 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajXJqKgPsK6zoCi32:-KnekaE7N18cfYpL4YIJ:b-hcuabd) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L60)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Did selectRow is being handled by TableData though. Do we want to duplicate that logic here and override TableData or do we want to add a deselectRow to TableData's didSelect?
</blockquote></details>

Don't duplicate the logic. Just override the didSelect and do this:
```swift
override func didSelect... {
  super.didSelect...
  tableView.deselectRow(at: indexPath, animated: true)
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194)*

**Comment by ecbrady** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift, line 60 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194#-KnajXJqKgPsK6zoCi32:-KnfOsjvDFwrL3c7Pea1:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/f64ab7863d19bd9f3c722adaa9178c8cac6684c4/byuSuite/Apps/CampusOperator/controller/CampusOperatorViewController.swift#L60)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't duplicate the logic. Just override the didSelect and do this:
```swift
override func didSelect... {
  super.didSelect...
  tableView.deselectRow(at: indexPath, animated: true)
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/194)*

**Pull request merged**
