### PR TITLE
hotfix/myClasses -> dev

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/315)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 96 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L7ztC-3BMBZRxJzHxYV:-L7ztC-3BMBZRxJzHxYW:bj4uobt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L96)):*
> ```Swift
> 			loadAllCurrentScheduleTableData()
> 		} else if let schedule = currentSchedule {
> 			let sortedSchedule = loadClassesWithChildClasses(schedule: schedule)
> ```

Could we move this log in into the schedule. Maybe a custom getter on `schedule.classesWithChildren`?

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 228 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L7zt_-05euu0IEAdNG_:-L7zt_-05euu0IEAdNGa:b-ura1l9) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L228)):*
> ```Swift
> 	}
> 	
> 	private func loadClassesWithChildClasses(schedule: StudentSchedule2) -> [StudentScheduleClass2] {
> ```

Could you show this to Geoff? Make sure he makes the same changes?

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 230 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L7ztWHn5YloMPDGaQFO:-L7ztWHn5YloMPDGaQFP:bkkgbwl) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L230)):*
> ```Swift
> 	private func loadClassesWithChildClasses(schedule: StudentSchedule2) -> [StudentScheduleClass2] {
> 		var allClasses = [StudentScheduleClass2]()
> 		for parentClass in schedule.classes {
> ```

This feels like it could use some higher order stuff...

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 33 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L7zti0k3Y2o-waeDq5D:-L7zti0k3Y2o-waeDq5E:bs6j6bo) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L33)):*
> ```Swift
> 			for dict in array {
> 				let temp = StudentScheduleClass2(dict: dict)
> 				//TODO: Currently, we add credit hours even for child classes. Some lab sections return credit hours even though they really don't have their own credit hours. So a 3 credit class with a lab will return 3 for the class section and 3 for the lab section. Check if there are cases where a child class lists credit hours that are NOT duplicates of the credit hours returned by the parent class. THEN change this as necessary. If necessary, there is a labQuizSeciton flag on StudentScheduleClass which may tell us that it is a lab section and the hours are duplicates.
> ```

Do it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 96 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315#-L7ztC-3BMBZRxJzHxYV:-L7zuPimWLsT6UKQxzi_:b4p7j2k) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L96)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could we move this log in into the schedule. Maybe a custom getter on `schedule.classesWithChildren`?
</blockquote></details>

This load? Yeah we can quite easily.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 228 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315#-L7zt_-05euu0IEAdNG_:-L7zuVFoz1sznF_CFjtK:bd8zhhy) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L228)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could you show this to Geoff? Make sure he makes the same changes?
</blockquote></details>

His already handled displaying child sections. I spoke with him to make sure we both did it in the same way.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 230 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315#-L7ztWHn5YloMPDGaQFO:-L7zuZeRbQnlKUzHlQ5W:b-d6rfa) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L230)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This feels like it could use some higher order stuff...
</blockquote></details>

I'll see what I can do.

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 33 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315#-L7zti0k3Y2o-waeDq5D:-L7zuDwZg5U6Q4l3Aykp:b-lu3xc2) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it?
</blockquote></details>

Geoff said that you told him to wait on this. Who should we talk to to check the business logic to see if there will ever be a child class that actually has it's own credit hours?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 96 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L7ztC-3BMBZRxJzHxYV:-L7zybz40Jk25sSwlWi6:b-nb2euy) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L96)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

This load? Yeah we can quite easily.
</blockquote></details>

Sorry. I meant move this method

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 33 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L7zti0k3Y2o-waeDq5D:-L7zytTY4hFcaoRZoFdY:b-of5h01) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L33)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Geoff said that you told him to wait on this. Who should we talk to to check the business logic to see if there will ever be a child class that actually has it's own credit hours?
</blockquote></details>

Oh gotcha. Talk to me about that when I get back in 45 minutes or so

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 96 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315#-L7ztC-3BMBZRxJzHxYV:-L88HfcgO93oPWp0-RC9:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L96)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Sorry. I meant move this method
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315)*

**Comment by ecbrady** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift, line 230 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315#-L7ztWHn5YloMPDGaQFO:-L88J8l6XN-l_sgogjhS:b-2g1n74) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Apps/MyClasses/controller/MyClassesListViewController.swift#L230)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I'll see what I can do.
</blockquote></details>

Okay I was able to simplify it slightly. But I don't think any actual higher order will work since I'm trying to add multiple things per parentClass

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 33 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L7zti0k3Y2o-waeDq5D:-L88KhNz94k4lpBkhjTG:b-b42p6f) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Oh gotcha. Talk to me about that when I get back in 45 minutes or so
</blockquote></details>

I'll be back at my desk in 30 minutes or so

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 47 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L88KqkKEbi9ezXJsUwM:-L88KqkKEbi9ezXJsUwN:bfqia98) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ae1decfc9d5160f507c995db6877e9d84ef5a939/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L47)):*
> ```Swift
> 	func loadClassListWithChildClasses() -> [StudentScheduleClass2] {
> 		var allClasses = [StudentScheduleClass2]()
> 		for parentClass in classes {
> ```

Use foreach

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 47 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315#-L88KqkKEbi9ezXJsUwM:-L88P_oDs1_2goMYcwVA:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ae1decfc9d5160f507c995db6877e9d84ef5a939/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L47)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use foreach
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/315)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 34 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L8DNw1J9j33uWDEAuBH:-L8DNw1J9j33uWDEAuBI:b-74kwfu) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6b08816c71943b5cfa8835e679c262f8b8fe668b/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L34)):*
> ```Swift
> 				let temp = StudentScheduleClass2(dict: dict)
> 				creditsCount += temp.creditHours?.asDouble() ?? 0
> 				if temp.sequence == "parent" {
> ```

Explain this one to me (I'm assuming we'll want to private let "parent")

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 34 at r2](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L8DNw1J9j33uWDEAuBH:-L8Y2FlU8hP4NFO0ButF:brsncn9) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/6b08816c71943b5cfa8835e679c262f8b8fe668b/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Explain this one to me (I'm assuming we'll want to private let "parent")
</blockquote></details>

Is this what you imagined?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315)*

**Comment by ecbrady** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift, line 33 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315#-L7zti0k3Y2o-waeDq5D:-L8YayAe7b-SkXdkI5qY:br969im) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/46f1b0ef35166e8043b7214b4926da84ad6d37f7/byuSuite/Classes/Reusable/Clients/StudentSchedule/StudentSchedule2.swift#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'll be back at my desk in 30 minutes or so
</blockquote></details>

Okay I spoke with Bill and he says we can ignore credit hours on child classes. I can explain it in more detail in person if you'd like. I spoke with Geoff to get it done in Android as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/315)*

**Pull request merged**
