### PR TITLE
hotfix/testingCenter -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/322)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[byuSuite/Classes/Reusable/Extensions.swift, line 977 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322#-L9fmm9V0KG0C5zpFkjj:-L9fmm9V0KG0C5zpFkjk:b-qdu5fn) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cbbab5cb05be80651a11dc7782830d7bd05f946c/byuSuite/Classes/Reusable/Extensions.swift#L977)):*
> ```Swift
> 
> extension UIView {
> 	func setGradientBackground(bottom: UIColor, top: UIColor) {
> ```

So does this function apply a gradient to the entire view? Or just part of the view (since we were thinking 25% or something like that)?

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 40 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322#-L9fmS7P1s4ZRVMkGR4z:-L9fmS7P1s4ZRVMkGR5-:b-px3tgt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cbbab5cb05be80651a11dc7782830d7bd05f946c/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L40)):*
> ```Swift
> 	override func awakeFromNib() {
> 		//Hide hidden view so that the gradient background does not appear until the image is loaded.
> 		infoView.isHidden = true
> ```

Can we do this from the storyboard?

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 41 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322#-L9fmYTKAJeS8E6aKTI-:-L9fmYTKAJeS8E6aKTI0:b-hceahw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cbbab5cb05be80651a11dc7782830d7bd05f946c/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L41)):*
> ```Swift
> 		//Hide hidden view so that the gradient background does not appear until the image is loaded.
> 		infoView.isHidden = true
> 		infoView.setGradientBackground(bottom: UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0), top: UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.0))
> ```

Is there a reason we can't use UIColor.black and UIColor.white?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Classes/Reusable/Extensions.swift, line 977 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322#-L9fmm9V0KG0C5zpFkjj:-L9fzt9a1rrvf2BGlMVd:b38oqin) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cbbab5cb05be80651a11dc7782830d7bd05f946c/byuSuite/Classes/Reusable/Extensions.swift#L977)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

So does this function apply a gradient to the entire view? Or just part of the view (since we were thinking 25% or something like that)?
</blockquote></details>

this is a gradient for whole view that it is on. That is why this method is only called on the infoView, as that is the block overlay.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 40 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322#-L9fmS7P1s4ZRVMkGR4z:-L9g-H4A9-_VZqHpw-2N:b37jfo5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cbbab5cb05be80651a11dc7782830d7bd05f946c/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we do this from the storyboard?
</blockquote></details>

yes, I will move it.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 41 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322#-L9fmYTKAJeS8E6aKTI-:-L9g-3VnAbbfcPrpHM_j:bap6smv) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cbbab5cb05be80651a11dc7782830d7bd05f946c/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is there a reason we can't use UIColor.black and UIColor.white?
</blockquote></details>

we cannot, because fading from black to white is not the same from fading from 100% black to 0% black (which is the effect we want).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322)*

**Comment by alexanderboswell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 40 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322#-L9fmS7P1s4ZRVMkGR4z:-L9pAp36Bak3K_AgePJc:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cbbab5cb05be80651a11dc7782830d7bd05f946c/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.

---

*[byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift, line 41 at r1](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322#-L9fmYTKAJeS8E6aKTI-:-L9pApWe5N-kffYtuxK4:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/cbbab5cb05be80651a11dc7782830d7bd05f946c/byuSuite/Classes/Reusable/UI/Cameras/CameraCell.swift#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could the first one at least be UIColor.black? And maybe we could create a UIColor.transparent?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/ios-byusuite/322)*

**Pull request merged**
