### PR TITLE
feature/learningSuite -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/236)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 35 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsoeicgN7KxbEbE-GeU:-KsoeicgN7KxbEbE-GeV:b76lkpz) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L35)):*
> ```objc
> @property (nonatomic) int                        callbackCounter;                   //keeps track of how many web requests have been made
> @property (nonatomic) LSCourse                  *course;
> @property (nonatomic) NSArray<LSCourse *>       *enrolledCourses;                   //courses the person is enrolled in
> ```

Try to remove this an instructor courses

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 42 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsoemtcRNGBNZxU7TLj:-KsoemtcRNGBNZxU7TLk:b-yliqyt) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L42)):*
> ```objc
> @property (nonatomic) NSArray<NSDictionary *>   *tableViewData;                     //enrolled and instructor courses loaded into a single data structure
> @property (nonatomic) SemesterButton            *semButton;
> @property (nonatomic) BOOL                       addededSemButton;
> ```

Why do we need this? I think we can just check if semButton is nil...

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 129 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofACs5x2BVHCkiK-0:-KsofACs5x2BVHCkiK-1:b-oxy0yx) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L129)):*
> ```objc
> -(void)addSemesterButton {
>     self.addededSemButton = YES;
>     NSMutableSet *enrolledSemesters = [NSMutableSet setWithArray:self.enrolledCoursesBySemester.allKeys];
> ```

Comments here

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 131 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofOn09YvSp75rRI26:-KsofOn09YvSp75rRI27:b-i1uy0u) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L131)):*
> ```objc
>     NSMutableSet *enrolledSemesters = [NSMutableSet setWithArray:self.enrolledCoursesBySemester.allKeys];
>     NSSet *instructorSemesters = [NSSet setWithArray:self.instructorCoursesBySemester.allKeys];
>     [enrolledSemesters unionSet:instructorSemesters];
> ```

Was union correct?

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 133 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofSTWDo88_F3l93bf:-KsofSTWDo88_F3l93bg:b-dbp2ph) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L133)):*
> ```objc
>     [enrolledSemesters unionSet:instructorSemesters];
>     NSArray *allSemesters = [enrolledSemesters allObjects];
>     NSSortDescriptor* sortDescriptor = [NSSortDescriptor sortDescriptorWithKey:nil ascending:NO selector:@selector(compare:)];
> ```

Why a nil key?

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 134 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofLK7OM1i1bzdHeef:-KsofLK7OM1i1bzdHeeg:b-58tuqp) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L134)):*
> ```objc
>     NSArray *allSemesters = [enrolledSemesters allObjects];
>     NSSortDescriptor* sortDescriptor = [NSSortDescriptor sortDescriptorWithKey:nil ascending:NO selector:@selector(compare:)];
>     allSemesters = [allSemesters sortedArrayUsingDescriptors:[NSArray arrayWithObject:sortDescriptor]];
> ```

You can use @[] here instead

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 139 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofXZFK17np63xVfnC:-KsofXZFK17np63xVfnD:b-gcf1bn) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L139)):*
> ```objc
>         return [YearTerm yearTermWithYearTerm:value];
>     }];
>     self.semButton = [SemesterButton buttonWithYearTerms:allYearTerms selectedYearTerm:allYearTerms[0] andDelegate:self];
> ```

What if allYearTerms is empty. Would this throw an error?

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 150 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-Ksoff4g8JApHuWLwMNg:-Ksoff4g8JApHuWLwMNh:b-8ialyy) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L150)):*
> ```objc
>         self.enrolledCourses = courses;
>         self.enrolledCoursesBySemester = [NSMutableDictionary dictionary];
>         for (LSCourse *course in courses) {
> ```

This logic is duplicated below. Let's see if we can put it in a function

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 253 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofyjkAp16pcau3MT9:-KsofyjkAp16pcau3MTA:b-phv2u2) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L253)):*
> ```objc
> 
> -(void)createButtonSucceeded:(SemesterButton *)button {
>     
> ```

Comment about why you don't need anything here

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 257 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-Ksog6JdJL38WrTlgy9-:-Ksog6JdJL38WrTlgy90:bpnbrdu) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L257)):*
> ```objc
> 
> -(void)createButtonFailed:(SemesterButton *)button {
>     [self.spinner stopAnimating];
> ```

I actually don't think you need anything here. You are passing in the semesters, right?

---

*[byuSuite/Apps/LearningSuite/model/LSClient.m, line 130 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-Ksoh-eJFP0piLZsH77X:-Ksoh-eJFP0piLZsH77Y:bky8qlz) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/model/LSClient.m#L130)):*
> ```objc
>                                             return [LSCourse courseWithDictionary:courseDict];
>                                         }];
>                                         NSSortDescriptor *yearTermDesc = [[NSSortDescriptor alloc] initWithKey:PERIOD_PROPERTY ascending:NO];
> ```

Do we need to sort the instructor ones the same way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236)*

**Comment by alexanderboswell** [comment]
Review status: 1 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 35 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsoeicgN7KxbEbE-GeU:-Ksy602Yx16rkMGJ0SfV:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Try to remove this an instructor courses
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 42 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsoemtcRNGBNZxU7TLj:-KsxwS8gXNqwTTJB8Od2:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why do we need this? I think we can just check if semButton is nil...
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 129 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofACs5x2BVHCkiK-0:-KsxwnVwCP9CNrMmrQYD:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L129)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comments here
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 131 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofOn09YvSp75rRI26:-Ksxwn4gTsMSvBa4Hhuf:bfrr5uj) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L131)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Was union correct?
</blockquote></details>

Yes, this worked correctly.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 133 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofSTWDo88_F3l93bf:-Ksy0mb7rThDptWDP0br:bk6dtin) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L133)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why a nil key?
</blockquote></details>

Im sure what I should put as the descriptor here as we are just sorting strings.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 134 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofLK7OM1i1bzdHeef:-Ksxy9U1QjZJCXxDHPlj:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L134)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can use @[] here instead
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 139 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofXZFK17np63xVfnC:-KsxyJYGFx3Rbmdiqwdj:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L139)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What if allYearTerms is empty. Would this throw an error?
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 150 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-Ksoff4g8JApHuWLwMNg:-Ksy4hurGl0Dg2E6naO9:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L150)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This logic is duplicated below. Let's see if we can put it in a function
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 253 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsofyjkAp16pcau3MT9:-KsxzhVF3NAIqLER8kkL:b-lim7gw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L253)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about why you don't need anything here
</blockquote></details>

We actually didn't need the method at all. So I removed it and was still working correctly.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 257 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-Ksog6JdJL38WrTlgy9-:-Ksy1It0nujLUEiCfiND:bfrpf76) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L257)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I actually don't think you need anything here. You are passing in the semesters, right?
</blockquote></details>

Was able to not include this method also, as it is optional in SemesterButton.

---

*[byuSuite/Apps/LearningSuite/model/LSClient.m, line 130 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-Ksoh-eJFP0piLZsH77X:-Ksy21AMLcY_JJtxC0Qs:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/ac13563a35182106706ef2e6924e1ed10e32944e/byuSuite/Apps/LearningSuite/model/LSClient.m#L130)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need to sort the instructor ones the same way?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 125 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsyDNSr_9zeyJMTsEtq:-KsyDNSr_9zeyJMTsEtr:b-8yf2e8) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/775cb5ffc1692b58b56415423c658872c2111496/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L125)):*
> ```objc
> -(void)addSemesterButton {
>     if (self.enrolledCoursesBySemester.allKeys.count != 0 || self.instructorCoursesBySemester.allKeys.count != 0) {
>         //This will get all of the courses in the last year that the person has either taught or been enrolled for.
> ```

I don't think this is correct... Won't this get all YEAR TERMS in the last year that the person has either taught or been enrolled in?

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 131 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsyD_9V2sj0AA_ytfJO:-KsyD_9V2sj0AA_ytfJP:b-kpy616) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/775cb5ffc1692b58b56415423c658872c2111496/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L131)):*
> ```objc
>         [enrolledSemesters unionSet:instructorSemesters];
>         NSArray *allSemesters = [enrolledSemesters allObjects];
>         NSSortDescriptor* sortDescriptor = [NSSortDescriptor sortDescriptorWithKey:nil ascending:NO selector:@selector(compare:)];
> ```

Should we use case insensitive compare?

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 136 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsyDm7vEU5T86TG-ynv:-KsyDm7vEU5T86TG-ynw:b-kmao1k) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/775cb5ffc1692b58b56415423c658872c2111496/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L136)):*
> ```objc
>             return [YearTerm yearTermWithYearTerm:value];
>         }];
>         self.semButton = [SemesterButton buttonWithYearTerms:allYearTerms selectedYearTerm:allYearTerms[0] andDelegate:self];
> ```

Wouldn't this still break if there are no year terms? Also, instead of using [0], use `first`

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 197 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsyEJ27XoRbfQSUUQbh:-KsyEJ27XoRbfQSUUQbi:b-xc5j58) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/775cb5ffc1692b58b56415423c658872c2111496/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L197)):*
> ```objc
>             NSMutableArray<NSDictionary *> *sections = [NSMutableArray<NSDictionary *> array];
>             
>             if (self.enrolledCoursesBySemester.allKeys.count > 0) {
> ```

Do you have to check the count of the keys? Or would this be the same as `self.enrolledCoursesBySemester.count`? See also below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 125 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsyDNSr_9zeyJMTsEtq:-KsyH2pgHMviFbz0Apql:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/775cb5ffc1692b58b56415423c658872c2111496/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L125)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't think this is correct... Won't this get all YEAR TERMS in the last year that the person has either taught or been enrolled in?
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 131 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsyD_9V2sj0AA_ytfJO:-KsyFqnjZuhTm3cf2NEc:bm8wmgh) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/775cb5ffc1692b58b56415423c658872c2111496/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L131)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Should we use case insensitive compare?
</blockquote></details>

Yes we should, Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 136 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsyDm7vEU5T86TG-ynv:-KsyH8NBo-yl2NXivgXq:bie34yj) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/775cb5ffc1692b58b56415423c658872c2111496/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L136)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Wouldn't this still break if there are no year terms? Also, instead of using [0], use `first`
</blockquote></details>

No this would not break because it will not get to this line unless there was at least one yearterm. The if statement at the top of the method accounts for that.

---

*[byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m, line 197 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236#-KsyEJ27XoRbfQSUUQbh:-KsyHbCmItcaTNEyPEYl:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/775cb5ffc1692b58b56415423c658872c2111496/byuSuite/Apps/LearningSuite/controller/LSClassesViewController.m#L197)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you have to check the count of the keys? Or would this be the same as `self.enrolledCoursesBySemester.count`? See also below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/236)*

**Pull request merged**
