### PR TITLE
feature/yTime -> dev

### PR DESCRIPTION
**Pull request by alexanderboswell**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ios-byusuite/276)

### CODE REVIEW

**Comment by alexanderboswell** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxooccQqNRv51CA4WDB:-KxooccQqNRv51CA4WDC:b-lfeadz) (no related file):*
Still need to do some testing with a user that has multiple jobs. Started the pr to review the other things before I am in at work again on thursday. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/YTime/controller/YTimeRootViewController.swift, line 73 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrvSFKKnDGFe0W60TC:-KxrvSFKKnDGFe0W60TD:b-3ax08t) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/controller/YTimeRootViewController.swift#L73)):*
> ```Swift
>     func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
>         if indexPath.section == 0, let cell = tableView.dequeueReusableCell(for: indexPath, identifier: "jobCell") as? YTimeJobTableViewCell {
>             cell.punchView.delegate = self //We added the delegate so that we could allow the view controller to handle the punch logic rather than each cell
> ```

Hmm... I think it might be better to make the delegate on the cell set the delegate on the punchView... I can be persuaded though. Why did you do it this way?

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 9 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxrw4u-Scvo_NiXXBbA:-Kxrw4u-Scvo_NiXXBbB:bxx9rf5) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L9)):*
> ```Swift
> //
> 
> import Foundation
> ```

Remove (inferred from UIKit)

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrwDhWgCDc2I2IP02o:-KxrwDhWgCDc2I2IP02p:b73qbf0) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L16)):*
> ```Swift
> }
> 
> let IN = "In"
> ```

What are all these? Should they be private?

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 33 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrxAZaV3QOCq1CMPCC:-KxrxAZaV3QOCq1CMPCD:bs1v9ov) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L33)):*
> ```Swift
> 			foregroundButton.setTitle(job.clockedIn ? OUT : IN, for: .normal)
> 			backgroundButton.setTitle(job.clockedIn ? CLOCKED_IN : CLOCKED_OUT, for: .normal)
> 			backgroundButton.contentHorizontalAlignment = job.clockedIn ? .left : .right
> ```

Were you able to get the text centering to work with this? Does it look like the previous version?

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 50 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxrxcd9oFbr1RvU4Z0a:-Kxrxcd9oFbr1RvU4Z0b:bf09jx1) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L50)):*
> ```Swift
> 	override func awakeFromNib() {
> 		foregroundButton.addGestureRecognizer(UIPanGestureRecognizer(target: self, action:#selector(handlePan)))
> 	}
> ```

Add extra space between functions

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 53 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrxifqvfQ93DfDzS0Y:-KxrxifqvfQ93DfDzS0Z:b8ryoy2) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L53)):*
> ```Swift
> 	@objc func handlePan(sender: UIPanGestureRecognizer) {
> 		if sender.state == .began || sender.state == .changed {
> 			let xPosition = sender.translation(in: self).x + (constraintedToLeft ? 0 : backgroundWidth)
> ```

Comments throughout this function

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 82 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxry6Oo-USVDFUq-0H9:-Kxry6Oo-USVDFUq-0HA:bo8nwlk) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L82)):*
> ```Swift
> 	}
> 	
> 	func constrainLeft() {
> ```

Can these be private? Can they be combined by passing in a boolean? Maybe something like this:
```swift
private func punch(in punchIn: Bool) {
...
}
```

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 82 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxryWde-rRisN1j1cou:-KxryWde-rRisN1j1cov:bqo6vm6) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L82)):*
> ```Swift
> 	}
> 	
> 	func constrainLeft() {
> ```

Should this actually be called punchOut?

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 94 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxryaJdywKC5ZoBNNdz:-KxryaJdywKC5ZoBNNe-:b-fhyzhw) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L94)):*
> ```Swift
> 	}
> 	
> 	func constrainRight() {
> ```

Should this be called punchIn?

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 96 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxrz63fk-BpU9T442N6:-Kxrz63fk-BpU9T442N7:b2tjlk9) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L96)):*
> ```Swift
> 	func constrainRight() {
> 		delegate?.createPunch(punchIn: true, job: job, sender: self)
> 		leftConstraint.constant = self.layer.frame.width * (2/3)
> ```

Isn't this what the computer property is for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[byuSuite/Apps/YTime/controller/YTimeRootViewController.swift, line 73 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrvSFKKnDGFe0W60TC:-KxxULswcQry3PECSDpc:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/controller/YTimeRootViewController.swift#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Hmm... I think it might be better to make the delegate on the cell set the delegate on the punchView... I can be persuaded though. Why did you do it this way?
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 9 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxrw4u-Scvo_NiXXBbA:-KxxIYAQLG6B0Z_baCIg:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L9)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove (inferred from UIKit)
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrwDhWgCDc2I2IP02o:-KxxIZdSFeK8X3_cteTo:bsp6v4e) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What are all these? Should they be private?
</blockquote></details>

Did you want the text as constants or just put in line as strings?

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 33 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrxAZaV3QOCq1CMPCC:-KxxXhqk5FX6k8l9jrtQ:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Were you able to get the text centering to work with this? Does it look like the previous version?
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 50 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxrxcd9oFbr1RvU4Z0a:-KxxIl3GLE0cxGNCS9m-:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L50)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add extra space between functions
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 53 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrxifqvfQ93DfDzS0Y:-KxxSN384xIylMz3UQ5y:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comments throughout this function
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 82 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxry6Oo-USVDFUq-0H9:-KxxMADVZxZwC1x_Ggjo:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L82)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can these be private? Can they be combined by passing in a boolean? Maybe something like this:
```swift
private func punch(in punchIn: Bool) {
...
}
```
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 82 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxryWde-rRisN1j1cou:-KxxMAWt86Gs2U_mdcfB:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L82)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Should this actually be called punchOut?
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 94 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxryaJdywKC5ZoBNNdz:-KxxMD-ECZTC1J1R26Qw:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L94)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Should this be called punchIn?
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 96 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxrz63fk-BpU9T442N6:-KxxJ1mB1CogZKYdDmcf:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L96)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Isn't this what the computer property is for?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrwDhWgCDc2I2IP02o:-Kxy2M9bFSqdLwKezkrd:b9spx37) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L16)):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

Did you want the text as constants or just put in line as strings?
</blockquote></details>

If they're only used once, feel free to inline them. I don't forsee these changing anytime soon

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 82 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxry6Oo-USVDFUq-0H9:-Kxy2t6adKkJACPePnlU:b9fqx61) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L82)):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Good job on the punch. Create a function combining constraintLeft and constraintRight as well to remove duplicate code

---

*[byuSuite/Apps/YTime/view/YTimeJobTableViewCell.swift, line 18 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxy3K_FVWQrPuMP8nUf:-Kxy3K_FVWQrPuMP8nUg:b-ye9141) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/bfefcc3e0dc0b520121f77d6fa5f984f90539358/byuSuite/Apps/YTime/view/YTimeJobTableViewCell.swift#L18)):*
> ```Swift
> 	@IBOutlet private weak var punchView: PunchView!
>     @IBOutlet private weak var errorLabel: UILabel!
>     
> ```

Spaces -> Tabs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by alexanderboswell** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxycQRTHi7RTTfnwLlr:-KxycQRTHi7RTTfnwLls:b-c7eeqy) (no related file):*
Is there a way to test it on PROD?

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxrwDhWgCDc2I2IP02o:-KxyaTmnZrek-jNLLnqv:b-e7ui3e) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

If they're only used once, feel free to inline them. I don't forsee these changing anytime soon
</blockquote></details>

They are used in two places. So I will keep them?

---

*[byuSuite/Apps/YTime/view/PunchView.swift, line 82 at r1](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxry6Oo-USVDFUq-0H9:-KxycJVhpwGFjHti9jCP:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/1dd1e3da1d77419d12c2aedffec645a5dce8179d/byuSuite/Apps/YTime/view/PunchView.swift#L82)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Good job on the punch. Create a function combining constraintLeft and constraintRight as well to remove duplicate code
</blockquote></details>

Done.

---

*[byuSuite/Apps/YTime/view/YTimeJobTableViewCell.swift, line 18 at r2](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-Kxy3K_FVWQrPuMP8nUf:-KxycPJo8LY6oP5hIgij:b-896fix) ([raw file](https://github.com/byu-oit/ios-byusuite/blob/bfefcc3e0dc0b520121f77d6fa5f984f90539358/byuSuite/Apps/YTime/view/YTimeJobTableViewCell.swift#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Spaces -> Tabs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxycQRTHi7RTTfnwLlr:-Kxycsy2SlQ0iWvnwCPL:b-5vc7cm) (no related file):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

Is there a way to test it on PROD?
</blockquote></details>

You can do it :) Just use it to clock out/in from here on out. Otherwise, we can do it and just have Robin nuke the punches

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxooccQqNRv51CA4WDB:-KxydYSVF-HuwV0Ja1e-:b-lij2qa) (no related file):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

Still need to do some testing with a user that has multiple jobs. Started the pr to review the other things before I am in at work again on thursday. 
</blockquote></details>

Do this by adding your own test job

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxycQRTHi7RTTfnwLlr:-KxydmcSL-_y4r0EPmiR:b2ni9bh) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can do it :) Just use it to clock out/in from here on out. Otherwise, we can do it and just have Robin nuke the punches
</blockquote></details>

ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxycQRTHi7RTTfnwLlr:-Kxye2y49yjcUfl9nlCl:bq56u07) (no related file):*
<details><summary><i>Previously, alexanderboswell (bozzy) wrote…</i></summary><blockquote>

ok.
</blockquote></details>

Mark this as done when it's been tested a couple times

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Comment by alexanderboswell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxooccQqNRv51CA4WDB:-KyWffyPjadBlhVadq3d:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do this by adding your own test job
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276#-KxycQRTHi7RTTfnwLlr:-KyWfgvqK8PebDRSIFK1:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Mark this as done when it's been tested a couple times
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ios-byusuite/276)*

**Pull request merged**
